### ISSUE TITLE
Myst build --pdf error:  TypeError: Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by salirezav** [scipy-conference/scipy_proceedings#1010]
Hello
I keep getting this message when trying to build (and export) my document to pdf or docx.

``` pwsh
❯ node -v        
v20.5.0

❯ npm -v 
9.8.0

❯ myst -v
v1.3.1
```

I have `mystmd` installed as well as `myst-parser` `myst-cli`.
I've run this command on a couple of different hardware and OSs but I keep getting the same error. 
I appreciate it if you could help me with this.

**Comment by rowanc1** [comment]
This should be fixed, this year we opted to not support PDFs before hand to avoid folks running into these errors. If it continues to be an issue next year, we can address it then!

Next year PDFs will be run in CI!
