### ISSUE TITLE
PDF export includes LaTeX style non-breaking space ~

### ISSUE THREAD

**Issue by matthewfeickert** [scipy-conference/scipy_proceedings#1033]
In conversation with @rowanc1 today we were discussing the great job that the team did with figuring out how to render ["Program 2"](https://github.com/scipy-conference/scipy_proceedings/blob/2024/papers/matthew_feickert/uncovering-higgs.md?plain=1#L27-L30) of (my) [How the Scientific Python ecosystem helps answer fundamental questions of the Universe](https://doi.org/10.25080/KMXN4784) submission for the PDF export, I noticed that the LaTeX style non-breaking spaces between measurements and units we used (i.e. `~`)

https://github.com/scipy-conference/scipy_proceedings/blob/f792cb1d88e62384a276be0f235c91a79fd23179/papers/matthew_feickert/introduction.md#L8-L9

is properly rendered in the [`myst` web view](https://proceedings.scipy.org/articles/KMXN4784#introduction)

[![image](https://github.com/user-attachments/assets/6d494030-54bc-4178-b563-222d050fb946)](https://proceedings.scipy.org/articles/KMXN4784#introduction)

but the `~` is getting displayed in the PDF export ([pdf_export.zip](https://github.com/user-attachments/files/17564297/pdf_export.zip))

![image](https://github.com/user-attachments/assets/39a3b04c-e264-46f8-a656-03403f36c9f8)

@rowanc1 suggested that I report this here. As the paper corresponding author I'm happy to help make any revisions necessary that might be needed to mitigate this.

---

I also want to commend the proceedings and Curvenote team for the amazing work here. That it is possible to have beautiful web native publications _and_ still very nice PDF exports is utterly fantastic and exciting!

**Comment by rowanc1** [comment]
These are now fixed, and deployed. Thanks for the kind words. :)
