### ISSUE TITLE
Backend code getting rendered in web export

### ISSUE THREAD

**Issue by matthewfeickert** [scipy-conference/scipy_proceedings#1034]
While writing Issue #1033 I noticed that just above ["Program 2"](https://github.com/scipy-conference/scipy_proceedings/blob/2024/papers/matthew_feickert/uncovering-higgs.md?plain=1#L27-L30) in [How the Scientific Python ecosystem helps answer fundamental questions of the Universe](https://doi.org/10.25080/KMXN4784) there is non-user-code from `myst`

```
#{ show raw.where(block: true): (it) => { show text: set text(size: 7pt) columns(2, it) } fullwidth[
```

getting rendered in the [web view](https://proceedings.scipy.org/articles/KMXN4784#cleaning-and-selecting-data) (which does not show up in the PDF export).

![image](https://github.com/user-attachments/assets/2c6a2f12-baae-40bf-91e4-5bcfd95e0d81)

(This is happening on both Chrome and Firefox, so I don't think it is a browser issue.)

**Comment by rowanc1** [comment]
Thank you - fixed, will deploy with the other changes shortly.

**Comment by matthewfeickert** [comment]
Fantastic! Thanks @rowanc1!
