### ISSUE TITLE
Allow building papers straight from Jupyter notebooks

### ISSUE THREAD

**Issue by stefanv** [scipy-conference/scipy_proceedings#109]

**Comment by rowanc1** [comment]
This is now possible using MyST Markdown! There were submissions that took advantage of this in 2024!

https://proceedings.scipy.org/articles/FGCJ9164

![image](https://github.com/user-attachments/assets/1d498390-bc22-429e-8f75-4bc8b7743d8a)

**Comment by stefanv** [comment]
Well, that only took a decade :sweat_smile:  Thanks @rowanc1! :muscle:

**Comment by rowanc1** [comment]
Slow and steady. :)

🚀
