### ISSUE TITLE
Delay in publishing proceedings is unacceptable

### ISSUE THREAD

**Issue by jzuhone** [scipy-conference/scipy_proceedings#113]
I don't mean to be harsh, but this long of a delay in publishing the proceedings is simply unacceptable. If the conference wants anyone to bother with submitting a proceedings next year, or for the foreseeable future for that matter, the conference organizers need to step up and completely overhaul this procedure. Some people actually rely on this conference proceedings to get their results out in a published format--it appears that this was a mistake.

**Comment by stefanv** [comment]
Thanks for your note John. I apologize for the delay, due to my moving
countries and jobs. I've been editing the introduction in the evenings
after work this week and am about to release. Your patience is appreciated.

**Comment by jzuhone** [comment]
If that's the case, then it is not your fault--it is the fault of whoever organized things this way. They shouldn't place that responsibility on one person.

**Comment by stefanv** [comment]
I'm afraid it's my fault for not communicating better. Again, my apologies.
I will have it ready by the end of the week.

**Comment by jakevdp** [comment]
Hi @jzuhone – I'd add that everything in the SciPy conference – from the scheduling to the website to talk selection to communication to sponsor organization to proceedings review & publication – is done by a team of community volunteers. If there's something about the organization that you think should change, the best way to make that happen is to become part of it!

**Comment by jzuhone** [comment]
Hi @jakevdp,

I would be interested in helping out--though at the moment there are some family health issues that might make my participation limited. However, if you could direct me to ways I can find out more about volunteering I would be interested.

**Comment by jakevdp** [comment]
@jzuhone – the 2015 conference chair is @kjordahl. If you get in touch with him, he'd be able to plug you in!

**Comment by katyhuff** [comment]
Since the 2014 proceedings are now published. I'm going to close this. Note that we are currently on track to publish the 2015 proceedings at the start of the conference.
