### ISSUE TITLE
PDFLaTeX error output when following README instructions

### ISSUE THREAD

**Issue by sbenthall** [scipy-conference/scipy_proceedings#118]
I've been following the instructions in the README and have gotten a PDFLaTeX error when trying to compile my (unedited) copy of the 00_vanderwalt paper. The culprit appears to be a missing file, ```paper_stats.json```

This is a gist of the error and preceding commands, copied from my terminal:

https://gist.github.com/sbenthall/67d0a39d8c7b9efdd961

**Comment by stefanv** [comment]
```
! LaTeX Error: File `IEEEtran.cls' not found.
```

You must install the IEEE transactions class--check the README for instructions.

**Comment by sbenthall** [comment]
works. thanks!

**Comment by argriffing** [comment]
http://en.wikipedia.org/wiki/Hawthorne_effect
