### ISSUE TITLE
[proceedings] multiple institutions?

### ISSUE THREAD

**Issue by bmcfee** [scipy-conference/scipy_proceedings#120]
In the 2015 proceedings template and build system, are multiple institutions per author accepted/supported?

It seems to work, in terms of generating the correct footnotes for affiliations, but I'm getting incorrect footnote markers next to the names.

Example source:
```rst
:author: First author
:email: foo@bar.baz
:institution: Home of Foo
:institution: Home of Bar

:author: Second author
:institution: Home of Bar

:author: Third author
:institution: Yet another place
```
and the rendered tex/pdf output:
![Author names](http://i.imgur.com/LnkG0ls.png)
...
![Footnotes](http://i.imgur.com/he7RBmI.png)

`Second author` should have a single dagger, and only `Third author` should have the double-dagger.

**Comment by bmcfee** [comment]
(clarification) actually the third institution is completely missing, so maybe multi-institution just doesn't work?

**Comment by stefanv** [comment]
This use-case isn't currently supported. Are you interested in making a
pull request, Brian?

**Comment by bmcfee** [comment]
Ok, thanks for clarifying!

I'll take a stab at fixing it, but no promises that it'll work!  (Beats writing, anyway! :))

Is the PR process the same as submission, just with a non-year branch name?

**Comment by stefanv** [comment]
Thanks, Brian! Yes, please make the changes on the master branch, update
the example paper to include the new feature, and then we'll merge the
changes into 2015 as well.

**Comment by katyhuff** [comment]
I think this can be closed now that this is merged. Closing.
