### ISSUE TITLE
question: is the page limit 7 or 8?

### ISSUE THREAD

**Issue by bmcfee** [scipy-conference/scipy_proceedings#122]
The readme says 7, but the email said 8.

**Comment by jackiekazil** [comment]
I don't know, but we went with 8. /cc @dmasad

**Comment by katyhuff** [comment]
@bmcfee and @jackiekazil :  Sorry about that. Go with 8. I'll fix the readme.

**Comment by katyhuff** [comment]
fixed with ba2993db5f9586d6ac0cb36ffdf31810a704e67f
