### ISSUE TITLE
Apparent python 3 incompatibility and possible PDFLaTeX error

### ISSUE THREAD

**Issue by michaelpacer** [scipy-conference/scipy_proceedings#125]
In following the instructions after forking the repo, cloning into a local directory, switching to the `2015` branch, making a personal directory (`papers/mike_pacer`), moving the example paper into my local directory and then trying to run `./make_paper.sh papers/mike_pacer/` I get an error. 

Specifically, 

```
  File "publisher/build_paper.py", line 123
    print "PDFLaTeX error output:"
                                 ^
SyntaxError: Missing parentheses in call to 'print'
Error building paper papers/mike_pacer/. Aborting.
```

Which looks like it both had some kind of problem related to running PDFLaTeX, as well as an error having to do with a python 3 incompatible print statement in its error printing code(though this just happened so I haven't had an opportunity to investigate more thoroughly yet).

**Comment by stefanv** [comment]
The build pipeline unfortunately has not been ported to Python 3 yet.  Please use Python 2 in the meantime.
