### ISSUE TITLE
only the first table gets booktabs

### ISSUE THREAD

**Issue by bmcfee** [scipy-conference/scipy_proceedings#127]
This can be observed in the demo doc, where table 1 gets booktabs and tables 2 and 3 do not.

This doesn't seem to be a property of the tables themselves, since rearranging them within the source document still ends up with the same behavior.

**Comment by stefanv** [comment]
Thanks for the report, Brian.  What is a booktab?  Tables has been one of the pain points of this pipeline so far.

**Comment by bmcfee** [comment]
Booktabs are the nice-looking tables: https://en.wikibooks.org/wiki/LaTeX/Tables#Using_booktabs

I can take a stab at fixing this, but probably not until later next week.  From a quick glance, it looks like maybe some state is getting reset (or not) in the `active_table` attribute: https://github.com/scipy-conference/scipy_proceedings/blob/master/publisher/writer/__init__.py#L50
