### ISSUE TITLE
Wrong year being rendered on PDFs

### ISSUE THREAD

**Issue by adamrp** [scipy-conference/scipy_proceedings#143]
Is the use of the year 2010 intentional in [these lines](https://github.com/scipy-conference/scipy_proceedings/blob/43d93c693a2c047e4b3e7967df44fbe7685ff67e/scipy_proc.json#L1-L11)? I believe it is causing the wrong year to be rendered at the top of the PDF (assuming it should be 2015).

![image](https://cloud.githubusercontent.com/assets/2574407/8171184/591eefbc-1373-11e5-86d3-9dd03bdec208.png)

**Comment by katyhuff** [comment]
@adamrp, I think you may have cloned the repo before I fixed that (a few weeks ago). You can see on the buildbot that everyone's pull requests are building with the right year: http://nipy.bic.berkeley.edu:5000/ .

I suspect this will be fixed if you merge the most recent version of the branch. Let me know.

**Comment by adamrp** [comment]
That worked! Thanks very much @katyhuff :smile:

**Comment by katyhuff** [comment]
happy to help!

**Comment by juanshishido** [comment]
@katyhuff, @stefanv:

I've seen a few issues related to this (e.g., #85, #110), so thought it best not to open a new one. In the `2016` branch, we're still seeing 2010 listed. I'm thinking the conference information just needs to be added (as noted here: https://github.com/scipy-conference/scipy_proceedings/issues/85#issuecomment-45977370).

Also, I checked out the `2015` branch to try to compile one of the papers and got: `ImportError: No module named 'rstmath'`. If this is needed, the README will have to be updated. Might it be easier to include a `requirements.txt` file?

**Comment by katyhuff** [comment]
The proceedings chairs this year are @sarostru and @sbenthall .

On Wed, May 25, 2016 at 11:06 AM, Juan Shishido <notifications@github.com>
wrote:

> @katyhuff <https://github.com/katyhuff>, @stefanv
> <https://github.com/stefanv>:
>
> I've seen a few issues related to this (e.g., #85
> <https://github.com/scipy-conference/scipy_proceedings/issues/85>, #110
> <https://github.com/scipy-conference/scipy_proceedings/issues/110>), so
> thought it best not to open a new one. In the 2016 branch, we're still
> seeing 2010 listed. I'm thinking the conference information just needs to
> be added (as noted here: #85 (comment)
> <https://github.com/scipy-conference/scipy_proceedings/issues/85#issuecomment-45977370>
> ).
>
> Also, I checked out the 2015 branch to try to compile one of the papers
> and got: ImportError: No module named 'rstmath'. If this is needed, the
> README will have to be updated. Might it be easier to include a
> requirements.txt file?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/issues/143#issuecomment-221656945>
>



-- 
http://katyhuff.github.com

**Comment by juanshishido** [comment]
Thanks for mentioning Scott and Seb, Katie!

**Comment by katyhuff** [comment]
No problem. I'm happy to help with this, I just would prefer them to be the
first line of defense if possible.

The year will get fixed when the proceedings are built in the final stage.
Don't worry about it for now. It will be fixed before they're on the scipy
site.  Lots of things happen between now and then.

Curious @juanshishido : Why did you need to checkout the 2015 branch to
test your build? Does the 2016 branch not build for you?


On Wed, May 25, 2016 at 11:33 AM, Juan Shishido <notifications@github.com>
wrote:

> Thanks for mentioning Scott and Seb, Katie!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/issues/143#issuecomment-221665317>
>



-- 
http://katyhuff.github.com

**Comment by juanshishido** [comment]
@katyhuff: I was just curious whether the compiled papers in the `2015` branch also had 2010 listed. This was before I realized `scipy_proc.json` controls that information. But, yes, the `2016` branch *does* build the papers 👍

**Comment by katyhuff** [comment]
oh good, phew!

On Wed, May 25, 2016 at 11:57 AM, Juan Shishido <notifications@github.com>
wrote:

> @katyhuff <https://github.com/katyhuff>: I was just curious whether the
> compiled papers in the 2015 branch also had 2010 listed. This was before
> I realized scipy_proc.json controls that information. But, yes, the 2016
> branch *does* build the papers 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/issues/143#issuecomment-221672524>
>



-- 
http://katyhuff.github.com

**Comment by sbenthall** [comment]
we are the first line of defense. the first line!
