### ISSUE TITLE
Fix Error in Mesa document

### ISSUE THREAD

**Issue by chendaniely** [scipy-conference/scipy_proceedings#174]
@katyhuff I'm taking the mesa conference proceeding and putting all the code into an ipython notebook to be used as a tutorial. I noticed the `from mesa.datacollector import DataCollector` line in the Data Collection section should read `from mesa.datacollection import DataCollector`

(datacollector to datacollection) should this be changed as a PR to be merged?

@dmasad @jackiekazil

**Comment by jackiekazil** [comment]
FWIW :+1: For the catch! If @katyhuff says it's okay, I am good with it.

**Comment by katyhuff** [comment]
Please do make a change as soon as possible, as a PR.

**Comment by jackiekazil** [comment]
@katyhuff I didn't know @chendaniely was going to submit PR or if I should have. 
@chendaniely, i hope I didn't step on your toes. :-)
PR is in.
