### ISSUE TITLE
Required latex packages.

### ISSUE THREAD

**Issue by rainwoodman** [scipy-conference/scipy_proceedings#183]
On a somewhat vanilla Fedora Linux system, the following packages are needed in order to build the example:

texlive-IEEEtran
texlive-everypage
texlive-draftwatermark
texlive-multirow

**Comment by stefanv** [comment]
Would you mind making a PR to update the README with installation
instructions for Fedora?

​

**Comment by rainwoodman** [comment]
closed via #188
