### ISSUE TITLE
no module named docutils

### ISSUE THREAD

**Issue by sbenthall** [scipy-conference/scipy_proceedings#186]
Getting this error on my attempt to build a copy of 00_vanderwalt paper on Ubuntu 14.04

```
./make_paper.sh papers/sebastian_benthallTraceback (most recent call last):
  File "publisher/build_paper.py", line 4, in <module>
    import docutils.core as dc
ImportError: No module named 'docutils'
```

**Comment by katyhuff** [comment]
do you have docutils installed?
Try 'pip install docutils' and run it again.

On Mon, May 23, 2016 at 1:53 PM, Sebastian Benthall <
notifications@github.com> wrote:

> Getting this error on my attempt to build a copy of 00_vanderwalt paper on
> Ubuntu 14.04
>
> ./make_paper.sh papers/sebastian_benthallTraceback (most recent call last):
>   File "publisher/build_paper.py", line 4, in <module>
>     import docutils.core as dc
> ImportError: No module named 'docutils'
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/issues/186>
>



-- 
http://katyhuff.github.com

**Comment by sbenthall** [comment]
This works.
I will update the README to make it clear that the Debian instructions will not install docutils correctly.

**Comment by sbenthall** [comment]
https://github.com/scipy-conference/scipy_proceedings/compare/master...sbenthall:patch-1

**Comment by katyhuff** [comment]
If you want to make an actual PR, you're going to want to click the "Create pull request" button at that link. . . https://github.com/scipy-conference/scipy_proceedings/compare/master...sbenthall:patch-1

**Comment by sbenthall** [comment]
don't know why i'm so stupid today. ticket closed.

**Comment by katyhuff** [comment]
Not stupid! You're getting things done !

On Mon, May 23, 2016 at 2:46 PM, Sebastian Benthall <
notifications@github.com> wrote:

> don't know why i'm so stupid today. ticket closed.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy-conference/scipy_proceedings/issues/186#issuecomment-221106082>
>



-- 
http://katyhuff.github.com
