### ISSUE TITLE
allow building papers straight from LaTeX

### ISSUE THREAD

**Issue by sbenthall** [scipy-conference/scipy_proceedings#189]
An issue that got raised as a result of last year's review process is that some more traditional academics would prefer if they could submit papers in LaTeX directly rather than as ReStructuredText

**Comment by stefanv** [comment]
The reason they can't do that is because then we can't review their papers on GitHub as easily with inline comments.

**Comment by stefanv** [comment]
(Closing, because this is technically already possible by inlining a bunch of LaTeX.)
