### ISSUE TITLE
Line number reported in error message is incorrect.

### ISSUE THREAD

**Issue by rainwoodman** [scipy-conference/scipy_proceedings#226]
This one is quite hard to fix. Because we run the rst converter on processed rst, the line number it throws is different from the original line number. 

I don't think it is possible to get the original line number. (Is there a #line instruction in restructured text?) 

As a practical alternative, we may want to catch the error, and print some context information from the processed rst to help the authors in finding the error.

**Comment by rowanc1** [comment]
There is much better error reporting down to position and column level information, including for latex, now that we are using myst markdown:

Here is a blog on that:
https://curvenote.com/blog/how-to-use-latex-with-myst-markdown#error-messages-partial-renderings

Docs for MyST Markdown are here:
https://mystmd.org/guide
