### ISSUE TITLE
Paper built on server has different layout properties for body text font than local builds

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#227]
Here is an image of what I mean. I thought our submission was within the 8 page limit because when built locally it is. 

It looks like there might be a "leading" (space between lines) issue as well as a definite font size difference for both headers and the body text. But it is not a general typesetting issue because the title and the abstract seem to be rendered with the same spacing properties in both cases.

Also the smallcaps Scipy proceedings header is a serif font in the build server's version and sans-serif in the locally built version. 

Not sure what these could be other than default LaTeX parameters that might differ between older and newer distributions. I'm going to guess that the server's is older than my local version, but I could be wrong. 

![image](https://cloud.githubusercontent.com/assets/2482408/16973424/70c16f4a-4de8-11e6-93a7-431c426a6b7b.png)

**Comment by michaelpacer** [comment]
Oh actually… There are slight differences in the formatting of the two with the abstract and title; there is more space between the title bar and the abstract in the build server version than in the locally built version.

**Comment by mpacer** [comment]
This was dealt with via https://github.com/scipy-conference/procbuild/pull/17.
