### ISSUE TITLE
Publish 2017 proceedings papers in Figshare Collection for DOIs?

### ISSUE THREAD

**Issue by kyleniemeyer** [scipy-conference/scipy_proceedings#237]
Hello all, this may have come up in conversation in past years (and I talked to @katyhuff a bit about this in Austin), but it would be nice to get the proceedings papers archived permanently (with DOIs) somewhere like Figshare.

Perhaps a Figshare collection could be created for all the papers? The past proceedings websites are all really slick so I don't propose getting rid of those, but this could supplement as a permanent archival for the papers themselves—the PDF links could be replaced with a link to the DOIs.

**Comment by sbenthall** [comment]
That's an intriguing idea. Could you please elaborate on what you have in mind?

**Comment by kyleniemeyer** [comment]
Figshare Collections are essentially a way to group a bunch of works (e.g., papers) *already* uploaded to Figshare (see https://figshare.com/blog/Unveiling_figshare_Collections_a_new_way_to_group_content/202). There's a guide to creating a collection [here](https://support.figshare.com/support/solutions/articles/6000128020-how-to-create-a-collection).

For example, there is a collection for all the posters and presentations from Force2016: https://force16.figshare.com

So, if this is desirable, it seems like it would be as simple as having each corresponding author submit their paper to Figshare, then have one of the proceedings editors create a collection from them all.

(This definitely isn't the only way to archive the proceedings papers, but it does seem fairly easy.)

**Comment by sbenthall** [comment]
Archiving proceedings papers with a DOI sounds good.

I'm wondering what concrete changes would need to be made to the proceedings software and process to make this happen easily.

I think you're suggesting that a new link should be added to each page about a talk/paper:

http://conference.scipy.org/proceedings/scipy2015/allen_downey.html

Do you think it's important that each author add their own papers to figshare, or could we have a 'Scipy' figshare account and load the papers ourselves?

**Comment by stefanv** [comment]
EuroSciPy has a way of doing this on arxiv. Nicolas Rougier or Nelle
Varoquaux may have more information.

**Comment by kyleniemeyer** [comment]
@sbenthall Regarding the link, I was originally thinking that the current link to the PDF could be replaced by a DOI link to the paper on Figshare, so that there's just a single PDF location (associated with the archive). This isn't a necessity, though.

I think the standard collection approach is to have authors upload their own work, and then an organizer creates a public collection out of them. This ensures that the paper is associated with the authors' account. Just playing around on Figshare right now, it does look like you can create an entry with authors that don't include you, so that's probably an option.

@stefanv I didn't originally suggest arXiv because it can be quite strict with the topics, and not all of the papers in the proceedings might fall under topics they consider appropriate for the arXiv (I've had papers that I've submitted be removed under moderation for falling out of appropriate topic areas). The benefit of Figshare, aside from being topic-neutral, would be the collection that groups all of the proceedings papers together in one place.

Figshare also now provides nice [altmetrics badges](https://www.altmetric.com/press/press-releases/figshare-integrates-altmetric/), as an added benefit.

**Comment by stefanv** [comment]
Here is the EuroSciPy proceedings I was referring to:
http://arxiv.org/html/1607.03971

Noted about arXiv perhaps not being the ideal location.

**Comment by sbenthall** [comment]
This is a great discussion.

My feeling is that getting these 2016 proceedings out has already dragged on way too long and it is too late in the game to introduce another step involving a round-trip between authors, figshare, back to .rst files. Pull requests have already been merged.

I'm going to change the header of this ticket to specify the **2017** proceedings.

Perhaps between now and next year those of us interested in improving the SciPy proceedings can meet up and put some more thought into the process. Collectively there's a lot of institutional memory and innovative thinking about scholarly publishing.

**Comment by kyleniemeyer** [comment]
@stefanv Oh that is interesting, I hadn't seen anything like that before.

@sbenthall While I of course hope to see something along these lines implemented in 2017 and beyond, I'm going to make a final plug for doing something here with the 2016 proceedings—at least for Figshare, there's no need for the source material, just an upload of the final PDF... and I imagine most authors would be willing to do that (fairly minor) step to get something a bit more permanent/archived and easily citable.

(I'll stop pushing for that now, and see if any others agree 😄)

**Comment by sbenthall** [comment]
@kyleniemeyer I'm personally running out of steam for making these kinds of changes this cycle. If you (or somebody else) wants to make a pull request for the README with new process information and the necessary changes to the publisher code, then we can review it as a possibility for this year.

**Comment by kyleniemeyer** [comment]
@sbenthall Fair enough, and I can only imagine—this is definitely something I would like for my own paper, so I'm happy to help streamline this process.

This year, I think the easiest thing would be to have authors upload their papers to figshare manually, and then give someone (me, in this case) the resulting DOI. Then I can manually add that to the publisher code to add it for the proceedings site. I'll create a PR to the README with instructions on uploading papers.

(In fact, I will offer to upload papers for other authors, if they don't want to do it themselves.)

Moving forward, if people agree to continue with Figshare, the whole process of both [uploading papers](https://docs.figshare.com/api/articles/#create-a-new-article) and [creating a collection](https://docs.figshare.com/api/collections/#create-a-new-collection) can be automated using the Figshare API. However, that will take a bit more work, and is likely appropriate for future proceedings.

**Comment by deniederhut** [comment]
Hi everyone! We currently publish the proceedings with DOI, and have started archiving slides and posters with Zenodo. Are we okay with closing this ticket?
