### ISSUE TITLE
Use archival link to video, not simply YouTube link

### ISSUE THREAD

**Issue by sbenthall** [scipy-conference/scipy_proceedings#242]
See https://github.com/scipy-conference/scipy_proceedings/issues/239#issuecomment-239353046

**Comment by mpacer** [comment]
I don't know if this is within scope for this year. We're still working on DOIs for the papers, I don't know nearly enough to work on DOIs for videos.

**Comment by deniederhut** [comment]
Hi everyone! I don't know about any services that do archiving of videos. Do you have something to recommend?

**Comment by deniederhut** [comment]
Then let's close for now - we can reopen if there is a way to move this forward.
