### ISSUE TITLE
Spin up proceedings server

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/scipy_proceedings#248]
title says it all, huff.

**Comment by katyhuff** [comment]
Okay, so on the phone call, @mpacer said he wanted to go through this process himself so that there was some knowledge transfer. Also, because he has physical access to the zibi server, that makes sense. Mike,   instructions follow:

**Comment by mpacer** [comment]
So… getting a warning when I first ran it:

    InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification 
    is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      InsecureRequestWarning)

And more problematically I'm trying to visit `http://zibi.bids.berkeley.edu:5000` and i'm getting seeing nothing on the server side. 

I'm running it from within screen but that shouldn't make a difference right?

**Comment by katyhuff** [comment]
@mpacer This is where physical proximity to zibi comes in. You can't unblock zibi's tcp port 5000 firewall via the command line. It requires someone with admin priviledges to log on to zibi in person and click "ok" in the popup (the popup will probably come up on zibi's screen when you run the script) It should only be required once.

If it doesn't pop up automatically you can open up her system preferences and do [this part about opening an applications firewall for all python applications on port 5000](http://www.macworld.co.uk/how-to/mac-software/how-open-specific-ports-in-os-x-1010-firewall-3616405/) in such a way that it includes the mike pacer user.

**Comment by mpacer** [comment]
kk we should be good now — i also set up a py36 env that already has permissions(i.e., the box was clicked & stefan signed the application package) and stefan reopened the firewall so now it should be good.

**Comment by katyhuff** [comment]
Great. Closing this issue.

**Comment by katyhuff** [comment]
Can this be closed @mpacer ?
