### ISSUE TITLE
DOI suffix for SciPy proceedings - input requested

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/scipy_proceedings#258]
In order to issue digital object identifiers (DOI) for items in the proceedings, we will need to come up with a schema for our DOI suffixes. Typically, these include some subset of the following:

- Journal title
- Year
- Volume
- Article ID

But could also be as simple as generating a unique identifier for each registered item. The goal is to have identifiers that are short enough to be easily displayed as links, but long enough to avoid reference collisions - [you can see some examples here.](https://support.crossref.org/hc/en-us/articles/214669823-Constructing-your-identifiers#samples) For Scipy, I imagine the bounds of our suffix options to be something like:

Most human readable: 10.25080/2017-usa-cs-0184 (year, country code, symposium, article number)

Least human readable: 10.25080/b2f1a8c8-ac0c-461a-998b-669608ff8063 (uuid4)

This issue is for collecting input on what should be included in the DOI suffix.

**Comment by Jabble** [comment]
Hi Dillon,
Librarian Anna here. A couple of questions: 
- Which service are you using to mint DOIs?
- Why are you interested in generating the suffixes yourself?

Off the bat, I'd like to recommend that you avoid human readable DOIs, and if it makes sense, let the registration agency generate unique suffixes for you. If you haven't already, look at the DOI Handbook: https://www.doi.org/hb.html

**Comment by mpacer** [comment]
Thanks Anna! We're all somewhat new to this process and eager to learn. Your expertise will be super helpful, so I expect we will be thanking you many times over throughout this process.

Is there a part of the handbook outside of https://www.doi.org/doi_handbook/2_Numbering.html#2.2.3 that is directly relevant to the suffix conversation? Or does that mostly cover it?

NB: We're working with CrossRef. Based on our communications with them and the content of the manual, it sounds like we (as the registrants) are expected to generate DOI suffixes. Is there a reason why a human readable doi is bad? It looks like it's decently standard for there to be some contentful substrings in the suffix to represent consistent information about the publisher in question. Is there a reason to _not_ have information present to make it easier to identify scipy DOIs as being from the scipy proceedings? My inclination would be to include `2017_scipy` somewhere in the suffix, but I'm open to the possibility that that might be suboptimal.

**Comment by Jabble** [comment]
That's a great place to look, also check out 1.6.3 DOI name syntax.

The best practice is to make sure that the identifier string is opaque (non‐meaningful). In registering a DOI, you (as the registrant) are committed to providing and maintaining basic information describing the object to which the DOI refers, called metadata. The metadata you register will include fields like URL, title, author, year, publisher, type. These fields depend on the CrossRef metadata schema. It's important not to conflate the identifier, which is meant to be globally unique and permanent, with the metadata. 

Ideally, we'd like to keep this permanent identifier referring to an object seperate from the metadata describing the object itself. The reason for this is that metadata may need updating and mistakes happen (shocking!). You should be free to change metadata into the (un)foreseeable future without conflicting with the identifier. The most likely update you will need to make is to the location (URL) of the object. However, if you construct the DOI partly from the name of the conference, what do you do if the name of the conference changes from scipi to stempy? This history shouldn't be built into the DOI. What if it isn't granular enough when you have twenty scipy conferences in a year? You may have done this to make it human readable, but it can very easily become human confusing. 

Lastly, human readable is pretty much irrelevant. The registration agency is promising to save the metadata you provide. The DOI can then be used as a link, which will resolve to the URL you've provided and maintained with the registration agency, and presumably this URL is where users will be able to access the object. 

I'm curious about how you intend to distribute the publications, and am happy to talk about this more in person or via phone call.
