### ISSUE TITLE
Add `citation_journal_title` to meta-data

### ISSUE THREAD

**Issue by stefanv** [scipy-conference/scipy_proceedings#299]
Currently, we use `citation_conference_title` only, but looks like Google Scholar doesn't index correctly.

See, e.g.

- http://conference.scipy.org/proceedings/scipy2014/collis.html
- https://scholar.google.com/citations?view_op=view_citation&hl=en&user=eMCDQDIAAAAJ&cstart=20&sortby=pubdate&citation_for_view=eMCDQDIAAAAJ:BqipwSGYUEgC

Who knows if that'll fix it (they may be grabbing this info from the PDF rather than the meta-tags, we have no way of knowing).

**Comment by stefanv** [comment]
Also note, from https://scholar.google.com/intl/en/scholar/inclusion.html#indexing:

> For journal and conference papers, provide the remaining bibliographic citation data in the following tags: citation_journal_title or citation_conference_title, citation_issn, citation_isbn, citation_volume, citation_issue, citation_firstpage, and citation_lastpage.

**Comment by mpacer** [comment]
Do they give semantics to what those names are to refer to anywhere?

**Comment by stefanv** [comment]
I could not find a good source; only the URLs linked to.

**Comment by deniederhut** [comment]
[This might be the best available reference](https://github.com/zotero/translators/blob/b76abc351e5d6c88f09b8159b532cb4415700458/Embedded%20Metadata.js#L40) -- I haven't been able to find anything from google scholar or highwire.
