### ISSUE TITLE
No easy way to test if all PRs work using make commands before merging PRs

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#308]
Right now you would need to either separately pull in and locally merge all of the PRs to the default branch in order to be able to test whether the `make` commands (e.g., `make proceedings-html`) work. 

This is inconvenient and makes consistent debugging and testing of those features challenging. 

We can probably address this by having a utility that will pull down the relevant branches to a new branch based on the same kind of logic that procbuild uses as party of the scipy_proceedings repo. 

Or we should figure out a different way to test these utilities on the actual papers before the merge has been made so that if any changes need to be made, authors can make them.

**Comment by rowanc1** [comment]
We have refactored to using github actions, which are run on every commit.

Automation still needs to be improved, however closing this in favour of a future issue!
