### ISSUE TITLE
Document use of status.sty 

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#311]
This is what adds the DRAFT watermark to each page. This should be documented. especially to distinguish between different statuses.

Notably I will be introducing the Conference Ready status (with a different opacity level and different text), which avoids the self-contradiction of calling them camera ready, which will be the final step after the videos are completed and we're all good to go.

**Comment by rowanc1** [comment]
The documentation certainly needs more work, but the process has changed significantly from 2017, closing this issue!

The creation of websites and PDFs is here:
https://mystmd.org/guide
