### ISSUE TITLE
Document location and use of logo.png

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#312]
In order to build the final proceedings requires getting the logo. It should be placed in logo.png. This should be documented somewhere (along with many other things).

**Comment by rowanc1** [comment]
Initial work to put this in a template was done this year for the 2024 proceedings, I think we will improve it next year as we are now using a templating system by MyST Markdown.

https://github.com/scipy-conference/scipy_proceedings_archive/blob/main/scipy2024/templates/scipy-preface/logo.png

Closing this so we can open a new issue on the process for 2025.
