### ISSUE TITLE
Currently, there is no global `proc-scipy-20*` built or placed under the bib directory

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#313]
Inside the html template, there are links to (for 2017) `./bib/proc-scipy-2017`. This is not a valid address because we don't create a global bib file.

Note, most of the existing scipy proceedings websites have this link and it's just broken: 

http://conference.scipy.org/proceedings/scipy2010/bib/proc-scipy-2010
http://conference.scipy.org/proceedings/scipy2011/bib/proc-scipy-2011
http://conference.scipy.org/proceedings/scipy2013/bib/proc-scipy-2013
http://conference.scipy.org/proceedings/scipy2014/bib/proc-scipy-2014
http://conference.scipy.org/proceedings/scipy2015/bib/proc-scipy-2015
http://conference.scipy.org/proceedings/scipy2016/bib/proc-scipy-2016

So, this is probably something that has been around since the beginning.

This shouldn't be hard to do I just don't want to fix it before releasing the proceedings.

**Comment by rowanc1** [comment]
These have now been moved to the archive repository:

https://github.com/scipy-conference/scipy_proceedings_archive/blob/main/scipy2015/proceedings/proc-scipy-2015.bib
