### ISSUE TITLE
The 2017 proceedings reported as 15th scipy in both the PDF and bib entry

### ISSUE THREAD

**Issue by narendramukherjee** [scipy-conference/scipy_proceedings#316]
@mpacer @katyhuff @dalippa @deniederhut 

Just wanted to bring to your notice that the papers in this year's proceedings are being shown as part of the 15th Scipy proceedings (and not 16th) in both the PDF and the bibtex entry. Is this correct/can this be fixed?

Thanks!

**Comment by deniederhut** [comment]
Whoops! Good catch. PR incoming.
