### ISSUE TITLE
Scipy 2017 papers contain "Proc of *15th* Python in Science Conf"

### ISSUE THREAD

**Issue by orbeckst** [scipy-conference/scipy_proceedings#319]
I had a quick look at the papers on http://conference.scipy.org/proceedings/scipy2017/ and in their header they claim to be from the **15th** Python in Science Conference whereas http://conference.scipy.org/proceedings/ says that this was the **16th**.

I don't know if you knew about it but I wanted to mention it just in case.

Thanks for all your hard work putting it together, looks really good!

**Comment by mpacer** [comment]
This was taken care of in the build process by #317.

**Comment by mpacer** [comment]
We still need to update the site though, but that'll wait until we have the full list of video links, which I believe are still coming in (for those papers that have video links).
