### ISSUE TITLE
Isolate make toc functionality for reuse

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#338]
`build_html.py` will fail if the table of contents has not yet been created, meaning it is implicitly dependent on `build_papers.py`. This means that if you `make clean`, you cannot `make html` before you `make papers` which seems… odd.

The table of contents can probably be made without running building the rest of the proceedings. We should isolate the toc making functionality and create it when making the proceedings if it's not already present.

**Comment by rowanc1** [comment]
The content for the website is now here:

https://github.com/scipy-conference/scipy_proceedings_archive/tree/main/landing

The toc is using MyST Markdown's TOC:
https://mystmd.org/guide/table-of-contents
