### ISSUE TITLE
Update templates to use jinja instead of tempita

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#339]
I think it'd be nicer if we used a more modern templating system. Jinja2 is what we use in a lot of the jupyter projects and it works pretty well. I've seen it used pretty widely as well.

It would also mean that we could have a templating system that had a bit more in the way of documentation & support without us needing to create that documentation.

I think it would also allow us to get around a lot of the current pseudotemplating that happens in our python code and the strange path tricks that we have to do to get the make scripts to work appropriately.

**Comment by rowanc1** [comment]
We have switched to using MyST Markdown for the scipy submissions! It does use Jinja under the hood.

https://mystmd.org/guide

New scipy template is here:
https://github.com/curvenote-templates/scipy
