### ISSUE TITLE
Package publisher more completely

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#340]
I think it would be nicer if we used a more traditional package/subpackage structure to organise the publisher rather than a collections of scripts that sort of work as modules. 

Not only will it make this functionality more portable, I think it'll make the logic flow easier to follow as currently a lot of stuff happens at the global scope of these scripts that doesn't need to happen in the global scope.

**Comment by rowanc1** [comment]
The majority of the process is now using [MyST Markdown](https://mystmd.org/guide), which has a community around it improving documentation and processing!
