### ISSUE TITLE
Better testing: refactoring large scripts into more modular functions

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#341]
We don't have much in the way of unittests for existing functionality. It makes it hard to make improvements without being afraid of breaking things. 

Breaking up the functionality from these gigantic scripts into collections of more self-contained functions would be a good first step as those functions could then be tested separately.

**Comment by rowanc1** [comment]
We are now using [MyST Markdown](https://mystmd.org/guide), which hopefully helps with the docs and community support for maintainence over time!
