### ISSUE TITLE
Fix running title of SciPy 2017 papers

### ISSUE THREAD

**Issue by mbeyeler** [scipy-conference/scipy_proceedings#343]
The 2017 PDFs still say "Proc of the 15th" conference, but SciPy 2017 was the 16th conference.

**Comment by deniederhut** [comment]
This was fixed... probably back in a588d613028755e6701ca0abe18d498d49e2947a but it looks like it didn't make it to deployment. In any case headers for 2017 look like this now:

<img width="548" alt="screenshot 2018-07-03 18 32 21" src="https://user-images.githubusercontent.com/6868396/42249232-e3ac5828-7eef-11e8-85ce-4733061de528.png">

So I'm closing this as fixed.
