### ISSUE TITLE
BUG: tex commands sneaking into html <p>

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/scipy_proceedings#347]
In building the html version of the proceedings, some of the tex commands seem to be passing through the escaping/replacing mechanism. Test case is in `_build/html/scott_sievert.html` which currently produces an html abstract that includes:

> Reducing the number of responses required can be done by adapting to previous responses with \textquotedbl{}adaptive\textquotedbl{} sampling algorithms, but these algorithms present a fundamental challenge when paired with crowdsourcing.

**Comment by rowanc1** [comment]
Resolved in the new system!

![image](https://github.com/user-attachments/assets/6a10d211-8597-4297-8670-ecdce1590384)
