### ISSUE TITLE
Weird parsing happening inside inline role declarations inside of captions

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#350]
In addition to the weirdness happening re: docutils 0.14 discussed in #349, there's additional weirdness going on in both docutils 0.12 and docutils 0.14 related to code in captions.

Specifically, if you have

```
:code:`my inline code`
```

inside of a caption for a nonclassed figure:

```rst
.. figure:: figure1.png

   This is the caption. :code:`chunk of code` inside of it. :label:`egfig` 
```

It instead is transformed into a call to `\DUroletitlereference` prefixed by the characters `:code:` rather than `DUrole{code}`, even if a definition for `DUrole{code}` is defined. 

For example, the above  case becomes:

```latex
\begin{figure}[]\noindent\makebox[\columnwidth][c]{\includegraphics[width=\columnwidth]{figure1.png}}
\caption{This is the caption. :code:\DUroletitlereference{chunk of code} inside of it. \DUrole{label}{egfig}}
\end{figure}
```

not sure why this is, but it's unrelated to our docutils version.

**Comment by rowanc1** [comment]
We are now using MyST Markdown, and these issues should be fixed!

https://mystmd.org/guide/figures
