### ISSUE TITLE
ORCID support

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#355]
We should have some way for authors to designate themselves with an ORCID that we link to in the pdf and the html, this will require changing the templates as well as the information that we extract from the rst's header.

@FatihAkici This is a more complicated feature to implement than in #353, so you should tackle that one first. Completing this should give you a better idea about the templating system and the way that metadata is collected from the documents and stored.

**Comment by mepa** [comment]
@stargaser, @deniederhut, should this issue be closed now that MR #532 has implemented the capability for authors to link their ORCID in the html? Or is this waiting on linking in the pdf also?

**Comment by deniederhut** [comment]
Good question - I don't remember if there were links on the HTML renders or not.

Related question, was this also implemented for slides and posters? No one submitted an orcid with their slides, but that doesn't mean that it wasn't possible. 
ivan-marroquin <notifications@github.com> wrote:
“@stargaser, @deniederhut, should this issue be closed now that MR #532 has implemented the capability for authors to link their ORCID in the html? Or is this waiting on linking in the pdf also?”

**Comment by stargaser** [comment]
For the papers, as I recall, we decided not to implement linking in the PDFs, and that a link on the HTML page for each paper was sufficient.

I don't know if the ORCID infrastructure will work for slides and posters.

**Comment by deniederhut** [comment]
Okay so it sounds like there is still work to do on this ticket for the slides and posters.
ivan-marroquin <notifications@github.com> wrote:
“For the papers, as I recall, we decided not to implement linking in the PDFs, and that a link on the HTML page for each paper was sufficient.

I don't know if the ORCID infrastructure will work for slides and posters.”
