### ISSUE TITLE
Move to python3 only

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#359]
We should plan the shift to using python3 only. 

We definitely should still support 3.4+ until the [end of its life in March 2019](https://devguide.python.org/#status-of-python-branches), so this is more about dropping support for python 2.7.

Perhaps this issue can act as a place for todos about what can improve once we make this transition.

**Comment by mpacer** [comment]
We should change the docs to represent this @FatihAkici

**Comment by deniederhut** [comment]
I believe (really hope) that we have already purged ourselves of Python 2 things. It would be good to check this to be certain.
