### ISSUE TITLE
Update instructions-for-authors to include "who can be an author"

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/scipy_proceedings#375]
[Instructions for authors](https://github.com/scipy-conference/scipy_proceedings#instructions-for-authors) should be updated to include information on group authorship. Specifically, to inform authors that we:

1. Allow projects to be listed as authors; and,
2. The project can be the sole author, first author, or affiliation of the authors; however, 
3. The corresponding author email must belong to a specific person

Issue prompted by discussion in #374.

**Comment by mpacer** [comment]
I think that there should be able to be more than one corresponding author (as suggested by @eseiver) but our current build server does not support this well. I'll open an issue about this separately, but I want to modify 3 to read "The corresponding author(s) email(s) must belong to specific people."
