### ISSUE TITLE
Is the build machine meant for prototyping draft builds?

### ISSUE THREAD

**Issue by choldgraf** [scipy-conference/scipy_proceedings#378]
Or is it meant only for uploading the "final" build?

The reason I ask is that if it's *not* meant for prototyping builds, maybe there would be value in making a Binder repo that serves an environment with latex etc installed and lets them demo the build there. Installing latex can be a beast sometimes so maybe this would save some people a bit of time. Just an idea!

**Comment by deniederhut** [comment]
Hi Chris! It is there for letting you see how your paper builds on our machinery (which I believe is what you mean by "prototyping draft builds").

**Comment by choldgraf** [comment]
cool - just want to make sure that it's OK to use it to, e.g., build upwards of 20 times in a row as I try to figure out what kind of formatting errors I have in my paper? :-)

**Comment by deniederhut** [comment]
Lol yes you may build to your heart's content.

**Comment by choldgraf** [comment]
just wanted to make sure :-)
