### ISSUE TITLE
Modify PR policies to reflect need to merge 2018 back into dev

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#381]
If people have PRs that start out against 2018 and switched to be pulled into dev, they will include the merge commits from dev to 2018, which looks odd.

We should make it part of our procedure to merge 2018 back into dev so the merge from dev to 2018 is included in master. 

I don't know another way to do this without asking people to rebase their branches onto dev.

So we should update the instructions to reflect that.

**Comment by deniederhut** [comment]
I'm not sure this is a problem any more. Closing unless you have objections.
