### ISSUE TITLE
Deprecate support for manually formatted references sections

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#412]
I would prefer people to use bibfiles rather than the current custom references section where we have little consistency in how the references are styled. This will be a similar policy to how we approach custom LaTeX (where in exceptional circumstances we allow it, but the case needs to explicitly be made).

The plan I'm proposing is: 

**for this year**: 
- We allow manual references but discourage it. 
- I will be explicitly asking authors to switch to using a bib-file in any case. 

**for next year**:
- no more example file including another way to handle references.
- we allow it in exceptional circumstances, but default to not allowing it

@dalippa @deniederhut @FatihAkici Do you have any objections to this? 

Credit to @jzf2101 for helping to convince me that this is a good policy move.

**Comment by deniederhut** [comment]
The submission deadline is hours away. It feels a bit late to be making policy changes for this year.

**Comment by mpacer** [comment]
@deniederhut That is only the initial submission deadline. I'm not suggesting that people will have needed to do this by now, but that I will be encouraging them to move to a bibfile in my comments on their papers. I just wanted to register my intentions in this regard here to have the discussion.

**Comment by rowanc1** [comment]
We now only are supporting inline citations to DOIs (https://mystmd.org/guide/citations) and bibfiles. The checks call out when we are missing DOIs to a reference.
