### ISSUE TITLE
Multiple corresponding authors

### ISSUE THREAD

**Issue by mpacer** [scipy-conference/scipy_proceedings#414]
Right now it seems that if we have more than one author listed as "corresponding author" then it includes a new entry in the footnote for each of those authors. As @eseiver noted on #374 corresponding authors can be multiple authors, however we should not allow non-person authors to list themselves as corresponding authors.

**Comment by deniederhut** [comment]
👍

**Comment by AntoineDujardin** [comment]
Right now, it seems that only one author is included.
Furthermore, the note is attached to the first author, whatever the actual corresponding author.
Can I have a non-first corresponding author?

**Comment by rowanc1** [comment]
There can now be multiple corresponding authors using MyST Markdown:

https://mystmd.org/guide/frontmatter#frontmatter-authors
