### ISSUE TITLE
Clean out the target `output` folder before building a new PDF

### ISSUE THREAD

**Issue by choldgraf** [scipy-conference/scipy_proceedings#422]
I've had a few gotcha moments where I was getting really cryptic errors, and it turned out to be because there was some cruft left over from a previous version of a paper build.

Would it be possible for `make_paper.sh` to clean out the output folder before building anything?

**Comment by deniederhut** [comment]
There is a `clean` directive in the Makefile that I think will do what you want. Or were you asking if we could have `make paper` always clean the build dir first?

**Comment by choldgraf** [comment]
> Or were you asking if we could have make paper always clean the build dir first?

yep, this one. Is there any reason not to do this?
