### ISSUE TITLE
WEB: header image doesn't scale properly

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/scipy_proceedings#428]
The header image for http://conference.scipy.org/proceedings/scipy2018/ isn't scaling properly on mobile, and I believe also not on non-Chrome desktop:

![screenshot_20180705-121013](https://user-images.githubusercontent.com/6868396/42599100-d2bdf14a-8523-11e8-99b1-c0f8fd5d9d83.png)

I imagine this is an issue with the CSS that we are serving.

**Comment by rowanc1** [comment]
The theme has been updated significantly:

![image](https://github.com/user-attachments/assets/c421fcb2-2e1d-44e9-9a7e-950cce71c9c5)
