### ISSUE TITLE
Bugs in rendering past proceedings

### ISSUE THREAD

**Issue by sbenthall** [scipy-conference/scipy_proceedings#438]
Hello. I'm not sure where's the best place to file this issue, but there appears to be something wrong with the process of publishing the conference proceedings to the server.

The bug is exposed by the fact that these two links:

https://conference.scipy.org/proceedings/scipy2015/pdfs/sebastian_benthall.pdf
https://conference.scipy.org/proceedings/scipy2016/pdfs/sebastian_benthall.pdf

Point to the same PDF, which corresponds to the 2016 submission, but not the 2015 submission.

https://github.com/scipy-conference/scipy_proceedings_2015/blob/master/papers/sebastian_benthall/sebastian_benthall.rst

This is perhaps embarassing since I was Proceedings chair in 2016, and it's quite possible that I inadvertently overwrote my own paper in the process of deploying the proceedings.

I'm wondering what process is in place to correct this, if any.

**Comment by deniederhut** [comment]
This should be fixed
