### ISSUE TITLE
Paper Authoring Questions re: Formatting & LaTeX packages

### ISSUE THREAD

**Issue by EdwardRaff** [scipy-conference/scipy_proceedings#456]
We are getting our 2019 paper ready, and have some questions, as we have not used rst before. In particular, how to use tell what the current number of pages is of the paper to make sure we abide by the page limits and make sure things look right. We would be happy sticking with pure LaTeX through overleaf, which the rst seems to be compiled to, but we don't see any information on how to compile rst to latex to pdf for the paper writing process (before we are ready to push it to github and issue a pull request). 

It's also not clear with LaTeX packages we can expect to be present. The example paper uses a PNG image for the figures, though we prefer to use Tikz and PGFplots to have LaTeX itself render the data and figures for us. 

Any guidance on this would be appreciated.

**Comment by deniederhut** [comment]
Hey there! Yes, the papers start as rst and are compiled down to PDFs through docutils. During this process, a bunch of templating and styles are applied to make sure the submitted papers have a consistent appearance.

If you want to see what your paper will look like after it's been compiled, you can do this locally by [running `make_paper.sh`](https://github.com/scipy-conference/scipy_proceedings#build-your-paper). If you open a PR (called `Paper: something something`) against the `2019` branch, our server will pull down your branch and attempt to build the paper remotely ([which you can see here](http://procbuild.scipy.org/)).

Hope this helps!
