### ISSUE TITLE
DRAFT in official proceedings page!

### ISSUE THREAD

**Issue by Teque5** [scipy-conference/scipy_proceedings#487]
On the SciPy [official proceedings](http://conference.scipy.org/proceedings/scipy2019/) page, all the PDFs are still marked as DRAFT. This should be fixed ASAP since the conference is now ongoing and the URL is going out.

**Comment by deniederhut** [comment]
Haha well they should still have a watermark, but that is not the correct watermark. 

BTW @stsievert was interested in chatting with you about some of the work that you are doing, if you are available to chat Thursday

**Comment by stsievert** [comment]
Copy. I’ll be around and try to connect with you.
