### ISSUE TITLE
Adopt a more defining info.json structure 

### ISSUE THREAD

**Issue by henrykironde** [scipy-conference/scipy_proceedings#511]
```j
{
  "authors": [
    {
      "name": "First Author",
      "orcid": "0000-0002...",
      "affiliation": 1
    },
    {
      "name": "second Author",
      "orcid": "0000-0045...",
      "affiliation": 1, 2
    }
  ],
  "affiliation": [
    {
      "name": "Department of Sci",
      "index": 1
    },
    {
      "name": "Department of Math",
      "index": 2
    }
  ],
  "title": "A test title",
  "description": "A brief description of what this object is"
}
```

Ref : Current [sample info.json](https://github.com/scipy-conference/scipy_proceedings/blob/2019/presentations/posters/example/info.json) 
Borrowed from [The Journal of Open Source Software](https://joss.theoj.org) 
I could put in a PR if accepted

**Comment by rowanc1** [comment]
We have adopted myst markdown, full capabilities here:

https://mystmd.org/guide/frontmatter#frontmatter-authors

It happens that this is exactly the same as the suggestion!
