### ISSUE TITLE
BUG: Zenodo DOI for pyhf poster is wrong

### ISSUE THREAD

**Issue by matthewfeickert** [scipy-conference/scipy_proceedings#518]
# Description

The Zenodo DOI for the pyhf poster (poster added in PR #502) is incorrectly entered in the [SciPy Zenodo entry for it](https://zenodo.org/record/3346186#.XT6FyHVKikA) though it is correctly given on [the proceedings page](http://conference.scipy.org/proceedings/scipy2019/slides.html). The DOI given [in the BibTeX](https://zenodo.org/record/3346186/export/hx#.XT6IKXVKikA) is [10.25080/Majora-7ddc1dd1-01f](https://doi.org/10.25080/Majora-7ddc1dd1-01f), however that is the DOI for ["Visualization of Bioinformatics Data with Dash Bio"](https://zenodo.org/record/3346213#.XT6IdHVKikA). The correct DOI for pyhf is [10.25080/Majora-7ddc1dd1-019](https://doi.org/10.25080/Majora-7ddc1dd1-019). So it seems that this is just an easy to make copy-paste error.

I would open a PR to fix this myself, except the error is not in the repo but in the SciPy Zenodo org, which I don't have access to.

Relatedly, thanks for taking on the extra work to publish the posters in the proceedings this year &mdash; it is quite nice.

**Comment by deniederhut** [comment]
Ugh sorry. Will have this fixed this tonight.

**Comment by matthewfeickert** [comment]
Nothing to be sorry about! This is a super easy mistake to make when our fingers decide they know what's best sometimes. :) Thanks for taking a look at this!

**Comment by deniederhut** [comment]
Sure thing. Does it look okay now?

**Comment by matthewfeickert** [comment]
> Does it look okay now?

LGTM! :rocket: Thanks very much for taking care of this so quickly!
