### ISSUE TITLE
Both first and last author names appear in references regardless of bibliography style

### ISSUE THREAD

**Issue by stsievert** [scipy-conference/scipy_proceedings#523]
`\bibliographystyle{abbrvnat}` has only shows the author's first initial and last name: https://www.overleaf.com/learn/latex/Natbib_bibliography_styles

However, even if I select this bibliography style, both author names are always shown.

Here's a minimal working example:

``` latex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}

\usepackage[square, numbers]{natbib}
\bibliographystyle{abbrvnat}

\begin{document}
Here are some hyperparameter optimization papers:
\cite{li2016hyperband}.

\cite{sievert2019better}


\bibliography{refs}{}
\bibliographystyle{plain}

\end{document}
```

``` bibtex
# refs.bib
@InProceedings{ sievert2019better,
  author    = { {S}cott {S}ievert and {T}om {A}ugspurger and {M}atthew {R}ocklin },
  title     = { {B}etter and faster hyperparameter optimization with {D}ask },
  booktitle = { {P}roceedings of the 18th {P}ython in {S}cience {C}onference },
  pages     = { 118 - 125 },
  year      = { 2019 },
  editor    = { {C}hris {C}alloway and {D}avid {L}ippa and {D}illon {N}iederhut and {D}avid {S}hupe },
  doi       = { 10.25080/Majora-7ddc1dd1-011 }
}

@article{li2016hyperband,
  title={Hyperband: A novel bandit-based approach to hyperparameter optimization},
  author={Li, Lisha and Jamieson, Kevin and DeSalvo, Giulia and Rostamizadeh, Afshin and Talwalkar, Ameet},
  journal={arXiv preprint arXiv:1603.06560},
  year={2016}
}
```

Output: 
<img width="518" alt="Screen Shot 2019-08-22 at 2 19 20 PM" src="https://user-images.githubusercontent.com/1320475/63543420-5523bf00-c512-11e9-80ab-995bd5802425.png">

**Comment by stsievert** [comment]
The references also look significantly different when `[square, numbers]` isn't passed to natbib:
<img width="522" alt="Screen Shot 2019-08-22 at 2 25 05 PM" src="https://user-images.githubusercontent.com/1320475/63543552-9ddb7800-c512-11e9-9215-d7d5cfc4c0f1.png">

**Comment by stsievert** [comment]
The braces in the Bibtex file are causing this.

If I change the `refs.bib` file to remove the braces in the `author` field, I get the correct output:
<img width="510" alt="Screen Shot 2019-08-22 at 2 26 27 PM" src="https://user-images.githubusercontent.com/1320475/63543763-0f1b2b00-c513-11e9-8b03-446057b098ad.png">

The changes I made were in `refs.bib` and are 

``` diff
-  author    = { {S}cott {S}ievert and {T}om {A}ugspurger and {M}atthew {R}ocklin },
+  author    = { Scott Sievert and Tom Augspurger and Matthew Rocklin },
```

**Comment by deniederhut** [comment]
🤔

I'm guessing from the commit history that bibtex was messing with the capitalization of people's names, but this was a bit before my time. @stefanv do remember the context around https://github.com/scipy-conference/scipy_proceedings/commit/8e6a9960f0e2214dd59a46aa4f604bbbee6c7ad9?

**Comment by rowanc1** [comment]
We have come across this with group names. If you are citing a team, ensure that the author name is wrapped in additional braces `{Team Name}`, so it is not treated as an author's first and last names.

```
@misc{pandas1,
  author    = {{The Pandas Development Team}},
  title     = {pandas-dev/pandas: Pandas},
  month     = feb,
  year      = {2020},
  publisher = {Zenodo},
  version   = {latest},
  url       = {https://doi.org/10.5281/zenodo.3509134},
}
```

This has been added to the template here:
https://github.com/scipy-conference/scipy_proceedings/blob/c13ec63884b356c2b7b63d6e958c6749e9524ed5/papers/00_myst_template/main.md?plain=1#L93C1-L94C1
