### ISSUE TITLE
Can we support papers submitted in markdown?

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/scipy_proceedings#524]
Kyle Niemeyer suggested that we consider accepting papers written in markdown, to lower the barrier of entry for people who only write restructured text once a year, which is the time they are submitting papers to SciPy. Can we learn from JOSS's publishing model and support papers in markdown?

**Comment by astrojuanlu** [comment]
[MyST](https://myst-parser.readthedocs.io/) supports the same directives and roles as reST, perhaps it's worth looking into it https://mystyc.herokuapp.com/

**Comment by stefanv** [comment]
myst-parser can produce a docutils AST, so should be possible: https://myst-parser.readthedocs.io/en/latest/apidocs/myst_parser/myst_parser.mdit_to_docutils.html

**Comment by rowanc1** [comment]
New papers are submitted in MyST (https://mystmd.org), LaTeX, or Jupyter Notebooks (as supplemental materials)!
