### ISSUE TITLE
Republish 2019 proceedings with slides submitted after deadline

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/scipy_proceedings#526]
We had two sets of slide decks come in after the deadline:

- https://github.com/scipy-conference/scipy_proceedings/pull/520
- https://github.com/scipy-conference/scipy_proceedings/pull/521

that we should put on the website and archive with Zenodo. The html page generation should work just fine, but the DOI assignment, metadata generation, and archiving will need to be done by hand.

**Comment by deniederhut** [comment]
@stsievert @astrofrog these should be up now

**Comment by stsievert** [comment]
Thanks @deniederhut!
