### ISSUE TITLE
Pin the version of docutils

### ISSUE THREAD

**Issue by mepa** [scipy-conference/scipy_proceedings#534]
Pin the version of `docutils` in `requirements.txt` to `0.14`.

**Context**
The current `requirements.txt` specifies `docutils >= 0.14` which, at the current time, installs `docutils==0.16`. 

When building a paper 
```
$ python publisher/build_paper.py papers/00_bibderwalt/ 
```
I see the error
```
...
".../scipy_proceedings/publisher/writer/__init__.py", line 386, in depart_table
    LaTeXTranslator.depart_table(self, node)
  File ".../scipy_proceedings/.env/lib/python3.8/site-packages/docutils/writers/latex2e/__init__.py", line 2966, in depart_table
    self.out.append('\n' + self.active_table.get_opening(width))
TypeError: <lambda>() takes 0 positional arguments but 1 was given
```

The error is due to a change in `get_opening` of the class `Table` between `docutils==0.14` and `docutils>0.14` (i.e., `0.15`, `0.16`).

The short-term fix is to pin the version in `requirements.txt` to `0.14`.

**Comment by deniederhut** [comment]
Closed in c9b89633a50a06da7dbb6dc97733803380efd0a0
