### ISSUE TITLE
Citations not working in rst

### ISSUE THREAD

**Issue by rkube** [scipy-conference/scipy_proceedings#537]
I'm adding my references into the rst as described in this example:
https://github.com/scipy-conference/scipy_proceedings/blob/2020/papers/00_bibderwalt/00_bibderwalt.rst

```rst
This is described in [Foo50]_

...

References
-----------
.. [Foo50] A. First and B. Second *Title of an interesting paper* Journ. Sci. 1 012003 (2020)
```

The output in the latex file is 
```
This is described in [?]
```
There is no reference section in the resulting pdf.
How can I get this working?

**Comment by deniederhut** [comment]
Hi! I'll need a bit more info to know what is breaking here. To start with, could I ask:

1. what are you typing in your terminal to build the paper?
2. have you defined a bibfile in the metadata at the top of your paper?

**Comment by rkube** [comment]
Right. I'm using the make_paper.sh script and am not defining a bibfile. The references work fine in the rst.

**Comment by deniederhut** [comment]
Your example builds for me locally -- to figure out what's going on, I'll need details about what you are doing.

>  I'm using the make_paper.sh script

Cool cool -- what are you typing into the terminal? As exact as possible please.

> and am not defining a bibfile

Could you copy and paste the metadata from the top of your rst file into this issue?

**Comment by rkube** [comment]
I'm calling make_paper.sh like this
```
cd scipy_proceedings
./make_paper.sh papers/first_last
```

Somehow it's working now. Thanks for looking into it.
