### ISSUE TITLE
tables don't work if they are all raw latex tables

### ISSUE THREAD

**Issue by summerswallow-whi** [scipy-conference/scipy_proceedings#544]
Due to the improper spacing, I've converted all my tables from rst tables to raw latex tables following the example given in `00_vanderwalt`. However, as soon as I delete the last of the rst tables, the make_paper.sh script breaks. The culprit I found is that `longtable` is not found. In comparing the difference in the source latex file, the `\usepackages('longtable')` is missing if an rst table isn't present.

For now the work around is to convert the simplest table to rst, but this is not an ideal solution as things can change due to the review and editorial process.

**Comment by deniederhut** [comment]
Hi! Sorry I missed this issue - I've been watching the PRs page for new papers, not the issues page. 

About this bug: when I remove all the rst tables from the 00_vanderwalt paper locally -- and leave only the latex one -- the paper compiles just fine.

Do you have an MRE that shows this failure? Or can you push a branch for me to look at?

**Comment by summerswallow-whi** [comment]
I don't get the issue of the missing longtable now, but it can't find \toprule now. I'm not a LaTex guru and merely copied the format produced by make_paper.sh to retain the look and feel. Looks like with rst tables booktable is included but not included if you don't have rst tables.

I will be submitting a pull request tomorrow and can refer to it. I'll update this issue when I make it tomorrow.

**Comment by deniederhut** [comment]
> I'm not a LaTex guru

Haha I think only Knuth can call themselves a LaTeX guru! But I'm happy to help try to figure out what's wrong if you run into any more issues. I'm going to close this ticket, but please open a new one or mention one of the proceedings co-chairs in a comment on your PR if you run into more problems.

**Comment by summerswallow-whi** [comment]
I've worked around the issue by including a small rst table, but `booktabs` is not loaded unless you have an rst table.
