### ISSUE TITLE
Paper compilation process is to time consuming.

### ISSUE THREAD

**Issue by rkube** [scipy-conference/scipy_proceedings#546]
Hi,
I find myself using too much time debugging the paper compilation process. While RST works find, the error messages of the make_paper script are useless in finding the error. For example, I've just used more than 10 minutes to find what
```

Runaway argument?
{ 
! Paragraph ended before \hyperlink was complete.
<to be read again> 
                   \par 
l.343 ...erence start-string without end-string.}}
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on paper.log.
```
means. This is after I've cut the paper file down to 322 lines.

I suggest that you use some time to make the submission process easier.

**Comment by deniederhut** [comment]
> I suggest that you use some time to make the submission process easier.

Sorry that you're frustrated! We're all volunteers here, so if you'd like to help us make the paper submission process easier you can always join the team!

**Comment by rkube** [comment]
Thanks Dillon. One issue I'm using a lot of time on is to find the line where rst syntax errors occur. Do you have any pointers where I can look into that issue?

**Comment by deniederhut** [comment]
So the tricky part here is that typically the errors occur after the code has been transpiled to latex. Maybe the easiest thing to do would be to track input line number is the docutils writer, whose class definition can be found here -> https://github.com/scipy-conference/scipy_proceedings/blob/3669cee309033ce98a846bf1471ae4ec5e463f22/publisher/writer/__init__.py#L27

**Comment by rowanc1** [comment]
We have switched to using [MyST Markdown](https://mystmd.org/guide) and Typst for the PDF compilations. This is now <1s for the entire build process for a paper, the `myst start` workflow has instant updates as well.

![image](https://github.com/user-attachments/assets/c047fc63-97dc-4949-a580-3c9dc681789f)
