### ISSUE TITLE
Add back README section on build system PRs

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/scipy_proceedings#572]
Currently our README links to the [following subsection](https://github.com/scipy-conference/scipy_proceedings/blob/2020/creating-build-system-prs) on how to submit a PR for modifying the build system (as opposed to adding a paper). That subsection doesn't actually exist anymore, so the address returns a 404. We should add that section back for contributors who would like to submit improvements to the build system.

**Comment by mepa** [comment]
Hey @deniederhut, it looks like the subsection exists but the internal refs to it are broken. Submitted a PR to fix it.
