### ISSUE TITLE
I'm still not seeing where nogil is imported.

### ISSUE THREAD

**Issue by rkube** [scipy-conference/scipy_proceedings#576]
I'm still not seeing where nogil is imported.

_Originally posted by @deniederhut in https://github.com/scipy-conference/scipy_proceedings/pull/560_

**Comment by rkube** [comment]
nogil doesn't require any imports:
https://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html

**Comment by deniederhut** [comment]
Hi! We don't usually file issues that copy comments made on PRs. That PR is the appropriate place to have this discussion.
