### ISSUE TITLE
That make sense. Could we say that explicitly? E.g. instead of "scientific discover", use "validate models for confined plasma" or "understand high energy plasmas"?

### ISSUE THREAD

**Issue by rkube** [scipy-conference/scipy_proceedings#577]
That make sense. Could we say that explicitly? E.g. instead of "scientific discover", use "validate models for confined plasma" or "understand high energy plasmas"?

_Originally posted by @deniederhut in https://github.com/scipy-conference/scipy_proceedings/pull/560_

Scientific discovery is much broader than "validate models for confined plasmas", some measurements are for example used to develop new models. It is also broader than only "understanding high energy plasmas", diagnostics allow us for example to understand plasma-surface interactions or the behavior of neutral gas populations in the periphery.

**Comment by deniederhut** [comment]
Hi! We don't usually file issues that copy comments made on PRs. That PR is the appropriate place to have this discussion.
