### ISSUE TITLE
I think you and I are looking at different tables. I mean this one:

### ISSUE THREAD

**Issue by rkube** [scipy-conference/scipy_proceedings#578]
I think you and I are looking at different tables. I mean this one:

<img width="430" alt="Screenshot 2020-06-28 15 15 41" src="https://user-images.githubusercontent.com/6868396/85957368-73d4bc80-b952-11ea-96bb-95ca672990e8.png">

_Originally posted by @deniederhut in https://github.com/scipy-conference/scipy_proceedings/pull/560_

Fixed table width

**Comment by deniederhut** [comment]
Hi! We don't usually file issues that copy comments made on PRs. That PR is the appropriate place to have this discussion.
