### ISSUE TITLE
SciPy 2020 proceedings DOI mismatch

### ISSUE THREAD

**Issue by matthewfeickert** [scipy-conference/scipy_proceedings#602]
Hi, it seems that there is a mismatch in the DOIs that are listed on the [Accepted Paper Slides page for SciPy 2020](http://conference.scipy.org/proceedings/scipy2020/slides.html) and on Zenodo. The DOI link for pyhf is

> pyhf: a pure Python statistical fitting library with tensors and autograd, Matthew Feickert
> [doi.org/10.25080/Majora-342d178e-022](https://doi.org/10.25080/Majora-342d178e-022)

but that redirects to the Zenodo entry for "Molecular infrastructure for modeling viruses with pythonic-mediated packages: pyF4all". If you click on the DOI link on the pyF4all: [doi.org/10.25080/Majora-342d178e-021](https://doi.org/10.25080/Majora-342d178e-021) that also redirects to the Pandera entry (which is 020). So as one would then expect the entry for 

> Bringing GPU Support to Datashader: A RAPIDS Case Study, Jon Mease
> [doi.org/10.25080/Majora-342d178e-023](https://doi.org/10.25080/Majora-342d178e-023)

redirects to the [pyhf entry on Zenodo](https://zenodo.org/record/3961236#.Xx8ETGNKiV4).

I haven't looked into this further yet, but it seems there's some off by 1 error happening.

cc @deniederhut

**Comment by deniederhut** [comment]
😬 let me take a look
ivan-marroquin <notifications@github.com> wrote:
“Hi, it seems that there is a mismatch in the DOIs that are listed on the Accepted Paper Slides page for SciPy 2020 and on Zenodo. The DOI link for pyhf is

“pyhf: a pure Python statistical fitting library with tensors and autograd, Matthew Feickert
 doi.org/10.25080/Majora-342d178e-022”

but that redirects to the Zenodo entry for "Molecular infrastructure for modeling viruses with pythonic-mediated packages: pyF4all"

If you click on the DOI link on the pyF4all: doi.org/10.25080/Majora-342d178e-021 that also redirects to the Pandera entry (which is 020). So as one would then expect the entry for

“Bringing GPU Support to Datashader: A RAPIDS Case Study, Jon Mease
 doi.org/10.25080/Majora-342d178e-023”

redirects to the pyhf entry on Zenodo.

I haven't looked into this further yet, but it seems there's some off by 1 error happening.

cc @deniederhut”

**Comment by matthewfeickert** [comment]
>  😬 let me take a look

Thanks @deniederhut &mdash; truly much appreciated. But this is obviously a low priority and a hard task (I'm trying to similarly get a large number of Zenodo DOIs for a conference at the moment).

**Comment by deniederhut** [comment]
So it looks like it was only the display DOIs that got jumbled -- everything got registered okay. The conference website has already been fixed, but updating the entries in Zenodo will take a bit longer.

**Comment by matthewfeickert** [comment]
> So it looks like it was only the display DOIs that got jumbled -- everything got registered okay. 

Sounds good! As long as I can know that

[![DOI](https://zenodo.org/badge/DOI/10.25080/Majora-342d178e-023.svg)](https://doi.org/10.25080/Majora-342d178e-023)

should stay attached to `pyhf` then that's all the information I need for now. Thanks!

**Comment by deniederhut** [comment]
Okay this should be fixed everywhere now. Please feel free to reopen if further issues.
