### ISSUE TITLE
Not able to open remote branch to open PR and submit poster PDF

### ISSUE THREAD

**Issue by ronikobrosly** [scipy-conference/scipy_proceedings#616]
Tried following the instructions on the README to open a PR and submit the draft of my poster presentation for SciPy 2021. I'm getting the following error:

```
rkobrosly@RKOBROSLY-MBP15 scipy_proceedings (roni_kobrosly_causal_curve) $ git push --set-upstream origin roni_kobrosly_causal_curve
ERROR: Permission to scipy-conference/scipy_proceedings.git denied to ronikobrosly.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Seems like I don't have rights to create a remote branch here? Any recommendations?

@deniederhut @stefanv @katyhuff

**Comment by stefanv** [comment]
Hi @ronikobrosly, 

I don't think this repository is used for posters, but maybe that changed recently @deniederhut? 

To submit a paper, you should fork the repository, push a branch to your own fork, and then use the Github interface to make a Pull Request. See the Github documentation for more information.

**Comment by ronikobrosly** [comment]
Oh in that case do you know which repo is used for posters? I've already published this work elsewhere, so won't be submitting one here.

**Comment by stargaser** [comment]
Hi @ronikobrosly, thank you for getting in touch about your poster. We did start accepting poster PDFs relatively recently, within the past two years.

This is the correct repository for submitting your poster. The instructions could be clearer and need some updates. You will need to fork the repository, and create your own branch from the `2021` branch. 

Posters are uploaded to Zenodo.org. The information in the json file is used when we upload, to fill in each author's name, affiliation and orcid.

**Comment by ronikobrosly** [comment]
Thanks @stargaser ! I'm about to open up the PR now.

**Comment by ronikobrosly** [comment]
Ok [I opened the PR](https://github.com/scipy-conference/scipy_proceedings/pull/617). So at this point my submission is complete and I should wait for reviewers to comment? @stargaser

**Comment by deniederhut** [comment]
Sorry to get here so late! @stargaser is correct, we do accept and publish posters (and slide decks), but typically wait until the conference is in session to solicit submissions. Poster submissions do not go through a review process, and are archived "as-is".
