### ISSUE TITLE
Is it too late to submit?

### ISSUE THREAD

**Issue by summerswallow-whi** [scipy-conference/scipy_proceedings#642]
@mepa, @cbcunc, @deniederhut, @stargaser.
I never received a follow-up email to my submission 111. As such I lost track of the deadline and only checked today. If you will still accept a first draft submission, I can probably have a submission by Tuesday. Suffice it to say, I don't want to dedicate the time if it is too late. Please let me know ASAP especially if you will accept it so I can work on it immediately.

Thanks.

**Comment by deniederhut** [comment]
Closed -- see https://github.com/scipy-conference/scipy_proceedings/pull/643
