### ISSUE TITLE
 make new branch in scipy-proceedings-test for 2022

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/scipy_proceedings#672]

**Comment by mepa** [comment]
Hey @deniederhut, does the new 2022 branch in scipy-proceedings-test need to contain the changes in the current 2022 branch of scipy-proceedings? Same question for dev branch.

**Comment by deniederhut** [comment]
No -- as long as it has the most recent changes from dev

**Comment by mepa** [comment]
Thanks, Dillon. Just pushed a new 2022 branch made from dev.
