### ISSUE TITLE
Misc notes on paper building process. 

### ISSUE THREAD

**Issue by Carreau** [scipy-conference/scipy_proceedings#687]
These are some misc notes on collaborating with someone to write one of the proceeding. 

1) I think the rst file should be removed from the output folder after build, or renamed. Reason begin there is a non zero risk for someone to start editing the things in output/build/paper.rst, and loose work later. 😭 

2) the default branch not being named `main` (or master), seem to be confusing. 

Thanks !

**Comment by deniederhut** [comment]
> the default branch not being named main (or master), seem to be confusing.

The logic there is that we have a different branch for each year of the conference, and that this keeps giant clumps of paper paraphernalia (like pngs) out of the dev, the development branch. I would be happy to chat with you about more clever ways of achieving these goals.

> I think the rst file should be removed from the output folder after build, or renamed.

Yup. We do have a `make clean` target, but that's probably not sufficient.

**Comment by Carreau** [comment]
> The logic there is that we have a different branch for each year of the conference, and that this keeps giant clumps of paper paraphernalia (like pngs) out of the dev, the development branch. I would be happy to chat with you about more clever ways of achieving these goals.

What about renaming master/main or whatever once the proceeding is published, so that at least during the submission period, it's a name that is commonly used ?

**Comment by deniederhut** [comment]
Not a bad idea -- I'll bring it up with the committee

**Comment by rowanc1** [comment]
- We have renamed to main.
- The build process is now `myst build` and `myst build --pdf`

Some links to docs:
- https://mystmd.org/guide/quickstart-myst-documents
- https://mystmd.org/guide/creating-pdf-documents
