### ISSUE TITLE
Spurious spacing in references

### ISSUE THREAD

**Issue by gpoore** [scipy-conference/scipy_proceedings#69]
Based on my experimentation, it looks like any reference beginning with an author initial must have a second line. Otherwise, there is extra spacing before the author name. And the extra spacing disappears if there isn't a period after the initial, or if there is only a period by itself.

Compare extra spacing before the `L.` produced by

```
.. [HEVEA]  L. Maranget. "HEVEA." http://hevea.inria.fr/.
```

versus the output of

```
.. [HEVEA] L. Maranget. "HEVEA."
           http://hevea.inria.fr/.
```

See the discussion in https://github.com/scipy/scipy_proceedings/pull/62#issuecomment-19340075.

**Comment by rowanc1** [comment]
We are now using MyST Markdown for the scipy proceedings! There is more about citations here:

https://mystmd.org/guide/citations
