### ISSUE TITLE
Paper builds locally but not on build server

### ISSUE THREAD

**Issue by rcjackson** [scipy-conference/scipy_proceedings#697]
@deniederhut @mepa My paper builds just fine on my local machine but when I submitted the PR the paper build fails. The title of the paper is "Improving PyDDA's atmospheric wind retrievals using automatic differentiation and Augmented Lagrangian methods."

**Comment by deniederhut** [comment]
Thanks for raising the issue! I've commented inline in the PR.

**Comment by rcjackson** [comment]
@deniederhut I can't seem to find your comment anywhere in the PR.

**Comment by deniederhut** [comment]
🤔  it must have been lost to the cosmos? But it looks like Meghann was able to help you out https://github.com/scipy-conference/scipy_proceedings/pull/696#pullrequestreview-987831919
