### ISSUE TITLE
Automated Bibliography Management

### ISSUE THREAD

**Issue by TheChymera** [scipy-conference/scipy_proceedings#72]
Hi guys, I am trying to use the scipy proceedings format to self-publish some scientific results (see https://github.com/TheChymera/OPR.OPR-Concepts-Guidelines/blob/master/paper/paper.rst#spi02 for the according guidelines paper I am writing). Previously I tried to do this via LaTeX ( https://github.com/TheChymera/OPR.Concepts-Guidelines-for-OPR ), and even though that approach was inferior - at least I could automatically build and compile my bibliography. 

Is there any more automated way to manage the bibliography of a paper written according to the scipy proceedings format? As it is I'm forced to write every bib entry by hand, and being a very cite-happy writer that's a pain.

**Comment by michaelpacer** [comment]
I think this pull request should address this issue: https://github.com/scipy-conference/scipy_proceedings/pull/166. 

You'll need to use bibtex (as you did in LaTeX), but it's far more automated than writing every bib entry by hand.

**Comment by katyhuff** [comment]
>I think this pull request should address this issue: #166.

I think what you mean, @michaelpacer is that PR #166 addresses this issue? In any case, I agree!! So... closing this! Nice work, folks.
