### ISSUE TITLE
PDF build failed- table content block and block quote issues

### ISSUE THREAD

**Issue by imoiwm** [scipy-conference/scipy_proceedings#728]
I'm experiencing the following errors when building our paper (fork from "ahy69195") locally as well as a prompt to download the missing, required file ```tex\latex\ieeetran\IEEEtran.cls``` from the package ```ieeetran```:

```
<string>:196: (WARNING/2) Content block expected for the "table" directive; none found.

.. table:: Five closest words of hand-selected terms compared between word2vec and dynamic word embeddings generated by our model :label:`compare`

<string>:214: (WARNING/2) Content block expected for the "table" directive; none found.

.. table:: The percentage and counts of our vocabulary sharing a given number of closest words (SCW for short) between word2vec and our model for time bucket #17. :label:`sharedclosest`

<string>:233: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
<string>:310: (WARNING/2) Content block expected for the "table" directive; none found.

.. table:: Distribution of medical terms and all terms within k-means clusters :label:`medterm`

<string>:336: (WARNING/2) Content block expected for the "table" directive; none found.

.. table:: Distribution of HIV terms and all terms within k-means clusters :label:`hivterm`
```

Even after confirming I installed the requirements from ```requirements.txt``` as well as attempting to manually install the ```ieeetran``` file, I was unable to download it due to a failure in solving environment.

All of the table-related errors stem from using the ```.. table:: ``` block, and when I remove them, only the block quote issue remains (as well as the ```ieeetran``` prompt):
```
<string>:233: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
```
However, that line is just a regular sentence from one of our paragraphs (copied below), and I'm not really sure what the cause is.
>Additionally, the corpus used spans over 20 years, allowing for metrics such as checking the closest word to leaders or titles, such as "president" or "NYC mayor" throughout time.

Also, if it's redundant or incorrect to use the ```.. table::``` block, then is there an alternative to the wide class ```:class: w``` that I could use to resolve a table not fitting into one column? Thank you.

**Comment by deniederhut** [comment]
> Even after confirming I installed the requirements from requirements.txt as well as attempting to manually install the ieeetran file, I was unable to download it due to a failure in solving environment.

IEEE transactions is a latex package -- not a python one -- so you would download it with whatever you used to install latex, e.g. tlmgr, mactex, etc.

> However, that line is just a regular sentence from one of our paragraphs (copied below), and I'm not really sure what the cause is.

Hard to say much about this error without the context around that line, but rst in general is pretty fussy about the appropriate amount of newlines between sections, so that might be a place to start.

BTW you can attach comments (like questions about errors) directly to lines in your source code file in the PR for this paper. Here's an example of Meghann doing this https://github.com/scipy-conference/scipy_proceedings/pull/701#discussion_r884279784.

**Comment by deniederhut** [comment]
The discussion has moved to the PR, so I'll close this ticket
