### ISSUE TITLE
PDF build failed because of Unicode characters ♁ or ⤶

### ISSUE THREAD

**Issue by astrojuanlu** [scipy-conference/scipy_proceedings#729]
I am trying to build #724 locally with some astronomical symbols, but I get these errors:

```
! Package inputenc Error: Unicode character ♁ (U+2641)                                                                 
(inputenc)                not set up for use with LaTeX.
```

I see several ways online to address it, but generally they involve using extra packages like https://mirrors.rit.edu/CTAN/macros/latex/contrib/wasysym/wasysym.pdf or doing some hackery. What would be the best way forward here?

**Comment by astrojuanlu** [comment]
Also happening with others like ⤶ (trying to use it to communicate line continuation in wide code outputs)

**Comment by astrojuanlu** [comment]
cc @jorgepiloto

**Comment by deniederhut** [comment]
We might be able to declare a new unicode character (e.g. following https://en.m.wikibooks.org/wiki/LaTeX/Special_Characters), but this will depend on us having that glyph in our font files, which we might not.

**Comment by stefanv** [comment]
Perhaps also try compiling with XeTeX instead of pdflatex.

**Comment by rowanc1** [comment]
This should be fixed going forward with out new PDF generation using MyST!

![image](https://github.com/user-attachments/assets/7efc0f00-2958-4d0b-abbc-13126439f514)

**Comment by astrojuanlu** [comment]
Woah these renders look _so nice_ ❤️ how can one rebuild an old paper with that template? Asking for a friend 😄

**Comment by rowanc1** [comment]
Our plan isn't to retroactively re-render PDFs that have already been published. The template is available [here](https://github.com/curvenote-templates/scipy), and we will continue to make this easier to install locally. Still needs some docs, but this is basically just using myst with a custom typst template!

**Comment by rowanc1** [comment]
That being said @astrojuanlu -- we are interested in back-porting web renders of all previous scipy papers! We have done 2023 and 2022 so far.

That effort is ongoing here:
https://github.com/scipy-conference/scipy_proceedings_archive

Thanks also for the kind words. :) Really excited about how amazing the new proceedings look!

https://proceedings.scipy.org
