### ISSUE TITLE
PythonTeX and .rst publishing

### ISSUE THREAD

**Issue by TheChymera** [scipy-conference/scipy_proceedings#73]
Hello, I am trying to write up some guidelines for revision-oriented publishing ( https://github.com/TheChymera/OPR.Concepts-Guidelines-for-OPR ). As it makes little sense to version figures over git - it would be awesome to have them plotted at compile time (which PythonTeX does). However, though I very much like LaTeX, I am thinking of maybe writing my papers as .rst (so that they can easily be read w/o requiring the user to compile them) - can PytonTeX be used from within .rst documents such as the ones used for the scipy proceedings?

**Comment by sbenthall** [comment]
What is the status of this ticket?

I just wrote #189 because last year we submitted our papers successfully in ReST.
