### ISSUE TITLE
Correct these citations

### ISSUE THREAD

**Issue by ojemebo** [scipy-conference/scipy_proceedings#737]
1) "Even familiar machine learning models have, buried in their guts, an assumption of the normal curve (e.g., LDA, gaussian naive Bayes, logistic & linear regression)"...__**a reference should be cited here to support this claim_**_
         one typo here:  a) remove the comma ',' between have and buried

2) "The normal curve has had a grip on us for some time; the aphorism by [Cra46] still rings true for many today"........._**this should be "The normal curve has had a grip on us for some time; the aphorism by Harold Cramer [Cra46] still rings true for many today:**_ 

3) "These call into question the usefulness of the normal curve and will be discussed in the following sections"..... **replace the following section with section labels (for example, section 2.1 or 3.0 or 402)**

4) " In the following sections"......._**replace the following section with section labels (for example, section 2.1 or 3.0 or 402)**_

**Comment by deniederhut** [comment]
Please see this comment https://github.com/scipy-conference/scipy_proceedings/issues/736#issuecomment-1146693611
