### ISSUE TITLE
There's a missing word in the Acknowledgements section and Author's institutional affiliation is missing

### ISSUE THREAD

**Issue by ojemebo** [scipy-conference/scipy_proceedings#739]
1) The author would like to Karlynn Chan and Rand R. Wilcox as well as Elizabeth Dlha and the entire Deepnote team for their
support of this project........_**the word 'thank' is missing between to and Karlynn**_ 

2) State your institutional affiliation below your name

**Comment by deniederhut** [comment]
Please see this comment https://github.com/scipy-conference/scipy_proceedings/issues/736#issuecomment-1146693611

**Comment by ojemebo** [comment]
> Please see this comment [#736 (comment)](https://github.com/scipy-conference/scipy_proceedings/issues/736#issuecomment-1146693611)

Since I am new to the GitHub platform, would you like to chat briefly over Zoom so you can show me exactly how to do this?. I'm available for this at your convenient time
