### ISSUE TITLE
First item in double indented numbered list has wrong spacing

### ISSUE THREAD

**Issue by scottshambaugh** [scipy-conference/scipy_proceedings#741]
In [my paper](https://github.com/scipy-conference/scipy_proceedings/pull/711), the following code has item a) rendering with a weird indent level. I can't figure out how to get it to align correctly. 

Things I've tried:

- Removing the four spaces after `following:    ` does not affect the output. 
- Changing the number of spaces before the alphabetical list does not change the output.
- Removing the extra newline between 3) and a) raises an error.
- Removing or increasing the indentation for a) also raises an error.

```
A summary of the process and data flow:

1) Instantiate a `Sim` object.
2) Add input variables to the sim with specified probability distributions.
3) Run the simulation. This executes the following:    

 a) Random percentiles :math:`p_i \in U[0,1]` are drawn `ndraws` times for each of the input variables.
 b) These percentiles are transformed into random values via the inverse cumulative density function of the target probability distribution :math:`x_i = F^{-1}(p_i)`.
 c) If nonnumeric inputs are desired, the numbers are converted to objects via a `nummap` dict.
```

![image](https://user-images.githubusercontent.com/14363975/176248489-4e377168-0cd1-4956-a312-6c8c52937b45.png)

**Comment by deniederhut** [comment]
Please don't open tickets about issues you are having with your paper -- we can address those in the PR
