### ISSUE TITLE
Revert merges of 2022 branch required for PR #707

### ISSUE THREAD

**Issue by cbcunc** [scipy-conference/scipy_proceedings#753]
@salirezav:

PR #707 contains several merge commits of the 2022 branch. This is preventing the proceedings build machinery from locating the paper to build as the PR now contains all papers thus far merged into the 2022 proceeding branch.

Please revert all merge commits of the 2022 branch in PR #707. You may wish to stash your work on the PR in case the reverts remove updates to you paper, as your merge commits are interleaved with your paper update commits.

Your paper cannot be merged into the proceedings until these merge commits are reverted and you paper can be built by procbuild.

The commits in need of reversion include:

* salirezav/scipy_proceedings@03df0e781f296506934f4ba614c0973b70a5e475
* salirezav/scipy_proceedings@cf812f4f0a3651e5f90765b9f4fb6caee0ee131a
* salirezav/scipy_proceedings@85e64ccf7d6d4549077e669d6c6ed9f3593f3196
* salirezav/scipy_proceedings@0415d1296c8f5d407807beb8f00dd8746de7e8ee

**Comment by salirezav** [comment]
I reverted all of the commits listed above. I hope everything is working correctly and hopefully I have not messed up anything.
Please let me know if I need to modify anything else.
