### ISSUE TITLE
Custom packages in latex

### ISSUE THREAD

**Issue by apaleyes** [scipy-conference/scipy_proceedings#796]
Hi!

I am trying to use latex template for the 2023 submission. I know it is considered in beta, but shall ask anyway. Is there a way to include custom commands or at least custom packages in the preamble? As far as I can see from the source code, it isn't possible, but would be very handy, e.g. for algorithms, math notation, subfigures/subcaptions and so on. It is very common for latex users to include custom packages in their latex files, so i think the build system should allow that.

Thanks!

**Comment by apaleyes** [comment]
An update: we found a workaround, but not quite sure how valid it is. In the file `publisher/build_paper.py` there is a variable `latex_header` that contains following line:

`%%% User specified packages and stylesheets`

If this line is replaced with necessary `usepackage` commands, everything seems to compile.

The problem with this workaround, of course, if the fact that it modifies the build tool, so we aren't quite sure if it will work for the PR. Any comments on this?

**Comment by deniederhut** [comment]
Hey! Sorry for the delayed response. Because we accept papers in different input formats, we try to keep the packages the same so that the compiled papers conform to a similar style. If there is a very useful package that we are missing, our preference would be to add it to the style file for everyone. What did you have in mind?

**Comment by apaleyes** [comment]
Thanks for checking this out! I understand the reason. Is the list of supported packages available somewhere?

For our specific use case, we were looking for a way to add algorithm environment, so that we could show algorithms via pseudocode with captions. Our workaround was using this:

   \usepackage{algorithm}
   \usepackage{algpseudocode}

But there are many ways to do algorithms in latex, and any of them would be fine.

**Comment by deniederhut** [comment]
The list of packages is [here](https://github.com/scipy-conference/scipy_proceedings/blob/2023/publisher/_static/scipy.sty), but does not have algpseudocode or algorithmic.

**Comment by deniederhut** [comment]
`algpseudocode` is now in the default style file

**Comment by deniederhut** [comment]
Actually this package is missing from the build server -- we'll add it there and I'll update when this is good to go

**Comment by deniederhut** [comment]
Okay everything should be working now.

**Comment by apaleyes** [comment]
Forgot to reply. Can confirm this works now, thanks!
