### ISSUE TITLE
Cannot rebuild already built latex paper

### ISSUE THREAD

**Issue by apaleyes** [scipy-conference/scipy_proceedings#797]
Hi!

Found a seemingly simple bug in the latex build. To reproduce:

1. Go to the repo root
2. Build the example paper (we assume python reqs and latex are already installed). All goes fine.

        ./make_paper.sh papers/00_texderwalt

3. Build the example paper again and observe the error

        ./make_paper.sh papers/00_texderwalt

Error text:

> Building: 00_texderwalt
> Traceback (most recent call last):
>   File "/home/ubuntu/projects/scipy_proceedings/publisher/build_paper.py", line 679, in <module>
>     build_paper(paper_id)
>   File "/home/ubuntu/projects/scipy_proceedings/publisher/build_paper.py", line 663, in build_paper
>     tex2tex(out_path, metadata_path)
>   File "/home/ubuntu/projects/scipy_proceedings/publisher/build_paper.py", line 532, in tex2tex
>     raise RuntimeError("Found more than one input .tex--not sure which "
> RuntimeError: Found more than one input .tex--not sure which one to use.
> Error building paper papers/00_texderwalt. Aborting.

Expected behavior is that the old paper render is overwritten with the new one. Confusing error, as there is certainly only one tex file in the `papers/00_texderwalt` dir! But turns out the issue is in the `output` directory. It can be worked around by removing the content of the output directory:

    rm -r output/00_texderwalt

But that seems unnecessary and probably easily fixed by the build script.

**Comment by deniederhut** [comment]
Thanks for the heads-up. I'll take a look.

**Comment by deniederhut** [comment]
Okay if you rebase your branch on 2023 you should be good to go

**Comment by apaleyes** [comment]
Works indeed, thanks!
