### ISSUE TITLE
Cannot add captions to code examples

### ISSUE THREAD

**Issue by asmeurer** [scipy-conference/scipy_proceedings#800]
I want to add a caption to a code example, but this feature appears to be Sphinx only, but the paper builder is using pure docutils. See https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-option-code-block-caption

Is there any way to achieve this?

**Comment by deniederhut** [comment]
😕 not that I'm aware of, but I am also not a docutils expert.

**Comment by rowanc1** [comment]
This is possible now with using myst!

https://mystmd.org/guide/code#code-blocks
