### ISSUE TITLE
Anybody have issues using eps with LaTeX beta. ?

### ISSUE THREAD

**Issue by summerswallow-whi** [scipy-conference/scipy_proceedings#807]
I get the following error. In past years I found eps worked best with the rst. If this is an issue, I can convert to another format I prefer a vector format as it preserves the lines better.

`Package pdftex.def Error: File `clique-eps-converted-to.pdf' not found: using
 draft setting.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.294 ...includegraphics[height=15em]{clique.eps}}`

**Comment by deniederhut** [comment]
I'm not really sure what to make of this error message without more information about what the file is and how you are entering into the rst. Is there a branch somewhere I can look at?

**Comment by summerswallow-whi** [comment]
Sorry. I must have miscommunicated. In the past I had no trouble with eps files in rst. However, when I try it in latex using your beta. I get that error.  It seems something is trying to do a conversion. We might get something checked in tomorrow. I think it ends up on a public site so once we get it on github I can direct you to it. Just as a backup plan. Do you know what vector graphic formats do work with the latex system?

**Comment by summerswallow-whi** [comment]
For anyone who might have this issue locally I was missing texlive-font-utils
