### ISSUE TITLE
Cannot use more than 7 institutions

### ISSUE THREAD

**Issue by asmeurer** [scipy-conference/scipy_proceedings#814]
If there are more than 7 different institutions in the authors list, the build fails with

```
! LaTeX Error: Counter too large.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.168           \renewcommand
                             {\leftmark}{PROC. OF THE 22nd PYTHON IN SCIENCE...
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on paper.log.
```

**Comment by deniederhut** [comment]
Mkay so I took a quick look at this, and this appears related to the limited number of footnote markers that latex supports. According to the internet there is a package that we can use to define additional footnote marks, but I don't think I'll be able to get this resolved today.  How many institutions were you hoping to have listed?

**Comment by asmeurer** [comment]
We managed to be just at the limit for our paper, so for now this isn't an issue for us.

**Comment by deniederhut** [comment]
Okay thanks for letting me know. I'll keep this issue open as a reminder for us to look into this again after the conference.

**Comment by rowanc1** [comment]
There is no limit going forward on number of institutions/affiliations for an author!

Documentation is here:
https://mystmd.org/guide/frontmatter#affiliations
