### ISSUE TITLE
Request: provide `minted` package for LaTeX builds?

### ISSUE THREAD

**Issue by ntjess** [scipy-conference/scipy_proceedings#827]
Thank you so much for providing the option to submit LaTeX papers this year!

Just one issue, there is no easy way to highlight code in a LaTeX submission. Even referencing the example file:
```tex
% in 00_texderwalt.tex

With code-highlighting:

\vspace{1mm}
\begin{Verbatim}[commandchars=\\\{\},fontsize=\footnotesize]
    \PY{k}{def} \PY{n+nf}{sum}\PY{p}{(}\PY{n}{a}\PY{p}{,} \PY{n}{b}\PY{p}{)}\PY{p}{:}
% ...
```

I assume this was not the intention. In the meantime, can you add `minted` (or `listings`, etc.) to the `scipy.sty` file so LaTeX authors can include code samples?

Bonus points if `metadata.yaml` or something similar would allow a user-specified set of `usepackage` entries 🙂

**Comment by deniederhut** [comment]
> I assume this was not the intention

😅

The restriction that we're operating under is that we want papers written in latex and restructuredtext to look the same. We didn't have enough time before paper submissions opened this year to find a good solution to produce the same syntax highlighting in both cases. So no, it was not what we wished would have happened, but yes, this is the supported version of latex code snippet highlighting for 2023. As you already noticed, the docutils commands are not very human legible.

**Comment by rowanc1** [comment]
The new system has syntax highlighting!

Both online:
![image](https://github.com/user-attachments/assets/c8697bc7-7c24-4c80-9b1c-26997422e4f6)

And in the PDF:
![image](https://github.com/user-attachments/assets/09c7fee3-d151-4629-987a-aa2cca4a85eb)
