### ISSUE TITLE
Procbuild shows no PDF

### ISSUE THREAD

**Issue by summerswallow-whi** [scipy-conference/scipy_proceedings#829]
Not sure why the build isn't happening. Locally make_paper.sh works. No error. I get no more information from procbuild than No PDF. Is there a way to access the build logs for this paper. I'm using the latex beta

Paper is Data Reduction Network.
https://github.com/scipy-conference/scipy_proceedings/pull/824

**Comment by deniederhut** [comment]
This is an issue with your paper, not with the build system. We'd prefer to keep comments about your paper in the PR about your paper.
