### ISSUE TITLE
Request: Can texlive-font-utils be included in the build process?

### ISSUE THREAD

**Issue by summerswallow-whi** [scipy-conference/scipy_proceedings#833]
Perhaps this may not be something you can do for this time around but this module is necessary in your make_paper.sh process in order for eps files to be used for figures. Without it `repstopdf` is not present which is what texlive uses to convert eps to pdf for inclusion. 

I think this would be convenient as eps is often a fairly universal format for vectorized drawings which has better resolution than pixmaps formats. 

The workaround if this cannot be implemented this year is to install texlive-font-utils locally and allow it to convert the eps to pdf then change you latex document to reference the pdf file. This process is fine until revision is needed to figures.

If not feasible for this year. I'd recommend consideration for next year. I think this was an issue in past years as well and not a function of .rst or .tex.

**Comment by deniederhut** [comment]
Closed in https://github.com/scipy-conference/procbuild/pull/68/files
