### ISSUE TITLE
Links in DOI not working anymore

### ISSUE THREAD

**Issue by chrisb83** [scipy-conference/scipy_proceedings#882]
The following page is accessible: https://conference.scipy.org/proceedings/

However, the links to the subdirectories like https://conference.scipy.org/proceedings/scipy2022 are broken. Hence, the links of DOIs linking to those proceedings do not work

**Comment by rowanc1** [comment]
This has been fixed with a redirect at the moment, we are working on an improved fix for all articles.

See https://github.com/scipy-conference/conference.scipy.org/pull/57 for more explanation.

**Comment by rowanc1** [comment]
This has all been resolved!
