### ISSUE TITLE
Problem Previewing Manuscript With Myst

### ISSUE THREAD

**Issue by hp2500** [scipy-conference/scipy_proceedings#905]
Hi there, I am trying to work on my proceedings manuscript and preview files with myst. I have installed mystmd and node, and closely followed the tutorial and other instructions. However, I am running into errors whenever I try to get the preview running. 

🔍 Querying template metadata from https://api.mystmd.org/templates/site/myst/article-theme
🐕 Fetching template from https://github.com/myst-templates/article-theme/archive/refs/heads/main.zip
💾 Saved template to path _build\templates\site\myst\article-theme
⤵️  Installing web libraries (can take up to 60 s)
npm error code ENOTDIR

npm error syscall mkdir
npm error path _build\templates\site\myst\article-theme\node_modules\@remix-run
npm error errno -4052
npm error ENOTDIR: not a directory, mkdir '_build\templates\site\myst\article-theme\node_modules\@remix-run'

npm error A complete log of this run can be found in: C:\Users\heinr\AppData\Local\npm-cache\_logs\2024-05-22T23_26_50_344Z-debug-0.log

Command failed: npm install
npm error code ENOTDIR
npm error syscall mkdir
npm error path _build\templates\site\myst\article-theme\node_modules\@remix-run
npm error errno -4052
npm error ENOTDIR: not a directory, mkdir '_build\templates\site\myst\article-theme\node_modules\@remix-run'
npm error A complete log of this run can be found in: C:\Users\heinr\AppData\Local\npm-cache\_logs\2024-05-22T23_26_50_344Z-debug-0.log

Myst CLI Versions:
 - node                        20.13.1     Required: >= 18.0.0
 - npm                          10.8.0     Required: >=8.6.0
 - myst                          1.2.4

Are you familiar with this problem. Do you have any recommendations on how to fix it?

**Comment by fwkoch** [comment]
Hey @hp2500 - thanks for posting your issue!

One possible cause of this error message may be related to running npm in a folder synced with google drive. Does this happen to be the case with your manuscript content...? If so, can you copying your files over to a local-only folder and try the build again there?

If this is not the case, we will need to dig a little more; can run myst in debug mode `myst start -d` and see if there is extra information logged to the console that you can copy here?

**Comment by stevejpurves** [comment]
@hp2500 I've tried to reproduce this on a Windows 11 PC matching the node, npm and myst versions you have but can't reproduce the issue you are seeing :( . 

If you can give us some more info on your setup and as @fwkoch mentioned whether you have network or synced folders in the mix somehow, that would be great.

**Comment by hp2500** [comment]
Thank you very much for your help with this @fwkoch @stevejpurves . My repo is indeed in a google drive directory. I will change the directory and try again. Your guidance is much appreciated.

**Comment by hp2500** [comment]
Confirming that I am now able to build the doc! Thank you for your help!

**Comment by rowanc1** [comment]
Glad this is fixed! The _build file shouldn't be committed to Git, no. It is already added to the `.gitignore` so you shouldn't need to delete it!
