### ISSUE TITLE
DOI Checks Failing on Papers

### ISSUE THREAD

**Issue by rowanc1** [scipy-conference/scipy_proceedings#935]
On some articles, the DOI checks that we are running for the authors are failing. We are still investigating and haven’t come up with a solution to the DOIs failing checks.

DOI had a service outage a while back that had them change their cloudflare config:
https://doi.statuspage.io/incidents/f4hrmd88c94l

I believe that some programatic access (e.g. a basic request without user-agents coming from github actions) to doi.org has been cut off, resulting in a 403 Forbidden when we ask if the DOI exists. We will add a fallback but that is going to take a bit of time. At this stage, some of the failing checks on scipy papers are because of this. I am hoping we will fix this in the coming few days.

cc @fwkoch @stevejpurves

**Comment by rowanc1** [comment]
This DOI failing checks are currently impacting #925, #918.

cc @TahiriNadia, @ameyxd, @hongsupshin

**Comment by ameyxd** [comment]
Also impacted: [#931](https://github.com/scipy-conference/scipy_proceedings/pull/931)

**Comment by fwkoch** [comment]
I have updated the checks to no longer fail when doi.org gives a bad response. Some of the PRs listed above are still failing for unrelated reasons.

For papers where all citations are defined in a `.bib` file, this will be enough - the checks will pass and the build will be fine. Only in cases where citations are built from DOIs referenced directly in the text will the build possibly have errors (there examples of this in the MyST paper). I'm continuing to work on a fix for those cases.

**Comment by rowanc1** [comment]
See some updates here:
- https://github.com/executablebooks/mystmd/pull/1285

**Comment by fwkoch** [comment]
Another fix here: https://github.com/executablebooks/mystmd/pull/1293

There are no longer any more DOI-related check failures 🥳

**Comment by ameyxd** [comment]
Good job folks! @rowanc1 @fwkoch 👏🏽
