### ISSUE TITLE
Incorrect Concurrency on the GitHub Action

### ISSUE THREAD

**Issue by rowanc1** [scipy-conference/scipy_proceedings#951]
@ejm714 @AmadiGabriel there were some issues raised here:

https://github.com/scipy-conference/scipy_proceedings/pull/947#issuecomment-2158900976

The current logic is to cancel based on branch name any concurrent actions. That needs to be updated to include the source repository as well, as most scipy submissions are all in branch 2024!

There should be a fix incoming shortly:
- https://github.com/curvenote/actions/issues/17

**Comment by fwkoch** [comment]
This is fixed in with the latest version of the action. Two submissions building simultaneously: 
![image](https://github.com/scipy-conference/scipy_proceedings/assets/9453731/c53de105-6a02-4f8f-8310-1f9cb7e3f6c2)
