### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by hydrogeohc** [scipy-conference/scipy_proceedings#987]
Hi all, 

I tried to create a PR from my fork within the "2024" branch. But it gave me this error message:
git push origin 2024
remote: Permission to scipy-conference/scipy_proceedings.git denied to hydrogeohc.
fatal: unable to access 'https://github.com/scipy-conference/scipy_proceedings.git/': The requested URL returned error: 403

Could anyone help me with it?

Thanks,
Ying-Jung Chen

**Comment by rowanc1** [comment]
Please open the PR through the GitHub user interface, which should be visible in your fork of the repo in your personal account. When pushing the changes, ensure that they are to your fork, where you should have the appropriate permissions.
